// Questions sorted by category (25 each)
// Question content is copied using AI, the coding format and main array is created by me
const questions = [
    {
        category: "2.1 quantitative analysis",
        questions: [
            {
                question: "What is the main purpose of carrying out a quantitative analysis on a consumer product?",
                options: ["To measure the exact mass of the container", 
                        "To determine the precise amount of a specific chemical present", 
                        "To identify all unknown substances in the product", 
                        "To change the chemical composition of the product"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following is an example of a consumer product often investigated using titration?",
                options: ["Soft drinks", 
                        "Plastic bottles", 
                        "Steel beams", 
                        "Pure oxygen"],
                correctAnswer: 0,
            },
            {
                question: "In an acid-base titration, what is the role of the indicator?",
                options: ["To speed up the reaction", 
                        "To change color at the equivalence point", 
                        "To increase the solubility of the acid", 
                        "To neutralise the base completely"],
                correctAnswer: 1,
            },
            {
                question: "Why must a burette be rinsed with the solution it will deliver before use?",
                options: ["To remove grease", 
                        "To avoid contamination and dilution of the solution", 
                        "To calibrate the burette scale", 
                        "To prevent air bubbles from forming"],
                correctAnswer: 1,
            },
            {
                question: "Which glassware is most appropriate for accurately measuring a known volume of solution in titration?",
                options: ["Beaker", 
                        "Measuring cylinder", 
                        "Volumetric pipette", 
                        "Conical flask"],
                correctAnswer: 2,
            },
            {
                question: "Why is a conical flask preferred over a beaker to hold the solution being titrated?",
                options: ["It reduces evaporation", 
                        "It allows swirling without spillage", 
                        "It measures volumes more accurately", 
                        "It makes the indicator more visible"],
                correctAnswer: 1,
            },
            {
                question: "What is the equivalence point in a titration?",
                options: ["When the solution turns pink", 
                        "When acid and base have reacted in stoichiometric proportions", 
                        "When all the solute has dissolved", 
                        "When the same volume of acid and base has been added"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following should NOT be used to measure the volume of solution delivered in a titration?",
                options: ["Burette", 
                        "Volumetric pipette", 
                        "Conical flask", 
                        "Graduated pipette"],
                correctAnswer: 2,
            },
            {
                question: "Why should the tip of the burette be filled with solution before beginning the titration?",
                options: ["To prevent leaks", 
                        "To ensure accurate volume readings", 
                        "To improve mixing", 
                        "To make the endpoint clearer"],
                correctAnswer: 1,
            },
            {
                question: "What is the main advantage of repeating a titration several times?",
                options: ["To make the solution stronger", 
                        "To obtain concordant results and improve reliability", 
                        "To reduce the amount of indicator used", 
                        "To change the colour of the endpoint"],
                correctAnswer: 1,
            },
            {
                question: "Which unit is commonly used for concentration in titration calculations?",
                options: ["g/L", 
                        "mol/L", 
                        "mg/mL", 
                        "ppm"],
                correctAnswer: 1,
            },
            {
                question: "What type of reaction occurs in a typical titration between hydrochloric acid and sodium hydroxide?",
                options: ["Redox", 
                        "Neutralisation", 
                        "Precipitation", 
                        "Decomposition"],
                correctAnswer: 1,
            },
            {
                question: "Why is a volumetric flask used to prepare standard solutions?",
                options: ["It is cheaper than a beaker", 
                        "It can hold hot liquids safely", 
                        "It allows precise measurement of a fixed volume", 
                        "It is easier to stir the solution in"],
                correctAnswer: 2,
            },
            {
                question: "Which of the following best defines a primary standard solution?",
                options: ["A solution used for washing glassware", 
                        "A solution of known and accurate concentration prepared from a pure solid", 
                        "A solution made up quickly for practice titrations", 
                        "Any solution containing an acid"],
                correctAnswer: 1,
            },
            {
                question: "Why must the solid used to prepare a primary standard be pure and stable?",
                options: ["To dissolve faster", 
                        "To ensure the calculated concentration is accurate", 
                        "To prevent colour changes in solution", 
                        "To reduce the need for titration"],
                correctAnswer: 1,
            },
            {
                question: "If a student overshoots the endpoint in a titration, what should they do?",
                options: ["Record the value anyway", 
                        "Add more indicator", 
                        "Repeat the titration carefully", 
                        "Start again without rinsing the glassware"],
                correctAnswer: 2,
            },
            {
                question: "Why should you add titrant dropwise near the endpoint?",
                options: ["To save time", 
                        "To avoid overshooting and improve accuracy", 
                        "To make the colour change more permanent", 
                        "To reduce the amount of indicator needed"],
                correctAnswer: 1,
            },
            {
                question: "Which of these could be a dependent variable in a titration investigation?",
                options: ["The volume of titrant added", 
                        "The concentration of standard solution", 
                        "The type of burette used", 
                        "The indicator chosen"],
                correctAnswer: 0,
            },
            {
                question: "What is the purpose of a blank titration?",
                options: ["To calibrate the burette", 
                        "To identify impurities in the solid", 
                        "To correct for any solution or indicator errors", 
                        "To test if the conical flask is clean"],
                correctAnswer: 2,
            },
            {
                question: "When diluting a solution, why is distilled water used instead of tap water?",
                options: ["It is cheaper", 
                        "It contains no ions that could affect the analysis", 
                        "It makes the colour of the indicator clearer", 
                        "It is easier to measure"],
                correctAnswer: 1,
            },
            {
                question: "If the titre values are 25.2 mL, 25.3 mL, and 25.8 mL, which results should be used to calculate the mean?",
                options: ["All three values", 
                        "Only the first value", 
                        "The two closest concordant results", 
                        "The largest and smallest values"],
                correctAnswer: 2,
            },
            {
                question: "What type of error is caused by not reading the meniscus at eye level?",
                options: ["Random error", 
                        "Systematic error", 
                        "Instrumental error", 
                        "Human error"],
                correctAnswer: 1,
            },
            {
                question: "In titration calculations, which formula is commonly used?",
                options: ["pH = -log[H+]", 
                        "n = c x V", 
                        "m = n x M", 
                        "V = d ÷ m"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following is a key safety precaution when handling strong acids or bases?",
                options: ["Never wear goggles", 
                        "Always pipette by mouth", 
                        "Wear protective clothing and rinse spills immediately", 
                        "Store in plastic bags"],
                correctAnswer: 2,
            },
            {
                question: "Why is it important to identify limitations in a titration investigation?",
                options: ["To make the solution weaker", 
                        "To evaluate sources of error and reliability of conclusions", 
                        "To reduce the number of trials required", 
                        "To ensure the burette stays clean"],
                correctAnswer: 1,
            },
        ],
    },

    {
        category: "2.4 structure & bonding",
        questions: [
            {
                question: "What type of bond involves the sharing of electrons between atoms?",
                options: ["Ionic bond", 
                        "Covalent bond", 
                        "Metallic bond", 
                        "Hydrogen bond"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following compounds is held together by ionic bonding?",
                options: ["NaCl", 
                        "H2O", 
                        "CO2", 
                        "O2"],
                correctAnswer: 0,
            },
            {
                question: "What is the correct electron geometry around a carbon atom in methane (CH4)?",
                options: ["Linear", 
                        "Bent", 
                        "Trigonal planar", 
                        "Tetrahedral"],
                correctAnswer: 3,
            },
            {
                question: "What type of intermolecular force is strongest in hydrogen fluoride (HF)?",
                options: ["Dispersion forces", 
                        "Dipole-dipole interactions", 
                        "Hydrogen bonding", 
                        "Ionic forces"],
                correctAnswer: 2,
            },
            {
                question: "Why does sodium chloride have a high melting point?",
                options: ["Because of strong metallic bonds", 
                        "Because of weak dispersion forces", 
                        "Because of strong electrostatic attractions between ions", 
                        "Because of covalent bonds between Na and Cl"],
                correctAnswer: 2,
            },
            {
                question: "What causes polar covalent bonds?",
                options: ["Unequal sharing of electrons due to electronegativity differences", 
                        "Equal sharing of electrons between atoms", 
                        "Transfer of electrons between atoms", 
                        "Movement of delocalised electrons"],
                correctAnswer: 0,
            },
            {
                question: "Which shape is predicted for BF3 using VSEPR theory?",
                options: ["Tetrahedral", 
                        "Trigonal planar", 
                        "Trigonal pyramidal", 
                        "Bent"],
                correctAnswer: 1,
            },
            {
                question: "What type of bonding explains the electrical conductivity of metals?",
                options: ["Covalent bonds", 
                        "Ionic bonds", 
                        "Metallic bonding with delocalised electrons", 
                        "Hydrogen bonding"],
                correctAnswer: 2,
            },
            {
                question: "Why does diamond not conduct electricity?",
                options: ["It has no ions", 
                        "It has no delocalised electrons", 
                        "It is molecular", 
                        "It contains impurities"],
                correctAnswer: 1,
            },
            {
                question: "Which molecular shape does water (H2O) have?",
                options: ["Linear", 
                        "Bent", 
                        "Trigonal planar", 
                        "Trigonal pyramidal"],
                correctAnswer: 1,
            },
            {
                question: "Why is graphite soft and slippery?",
                options: ["It has weak dispersion forces between layers", 
                        "It has strong covalent bonds between all carbon atoms", 
                        "It contains metallic bonding", 
                        "It has hydrogen bonding between layers"],
                correctAnswer: 0,
            },
            {
                question: "Which molecule is non-polar overall despite having polar bonds?",
                options: ["H2O", 
                        "NH3", 
                        "CO2", 
                        "HCl"],
                correctAnswer: 2,
            },
            {
                question: "What type of forces hold molecular solids together?",
                options: ["Electrostatic forces between ions", 
                        "Covalent bonds in a 3D lattice", 
                        "Intermolecular forces", 
                        "Metallic bonds"],
                correctAnswer: 2,
            },
            {
                question: "What is the bond angle in ammonia (NH3)?",
                options: ["180°", 
                        "120°", 
                        "109.5°", 
                        "107°"],
                correctAnswer: 3,
            },
            {
                question: "Which factor determines whether a molecule is polar overall?",
                options: ["The number of bonds", 
                        "The symmetry of the molecule and bond dipoles", 
                        "The size of the atoms", 
                        "The molecular mass"],
                correctAnswer: 1,
            },
            {
                question: "Which type of bonding is present in potassium metal (K)?",
                options: ["Ionic", 
                        "Covalent", 
                        "Metallic", 
                        "Hydrogen"],
                correctAnswer: 2,
            },
            {
                question: "Why do molecular substances generally have low melting points?",
                options: ["Because they have weak intermolecular forces", 
                        "Because they have strong metallic bonding", 
                        "Because they have ionic lattices", 
                        "Because they contain delocalised electrons"],
                correctAnswer: 0,
            },
            {
                question: "What shape is predicted for carbon dioxide (CO2)?",
                options: ["Bent", 
                        "Linear", 
                        "Trigonal planar", 
                        "Tetrahedral"],
                correctAnswer: 1,
            },
            {
                question: "Why does graphite conduct electricity but diamond does not?",
                options: ["Graphite has free-moving ions, diamond does not", 
                        "Graphite has delocalised electrons, diamond does not", 
                        "Diamond is more polar than graphite", 
                        "Diamond contains dispersion forces"],
                correctAnswer: 1,
            },
            {
                question: "What type of bonding is present within the molecules of H2O?",
                options: ["Ionic bonds", 
                        "Polar covalent bonds", 
                        "Metallic bonds", 
                        "Dispersion forces"],
                correctAnswer: 1,
            },
            {
                question: "What happens to bond polarity as the electronegativity difference between two atoms increases?",
                options: ["It decreases", 
                        "It stays the same", 
                        "It increases", 
                        "It becomes metallic"],
                correctAnswer: 2,
            },
            {
                question: "Which of the following substances has a giant covalent network structure?",
                options: ["CO2", 
                        "NaCl", 
                        "SiO2", 
                        "NH3"],
                correctAnswer: 2,
            },
            {
                question: "Which intermolecular force is present in all molecular substances?",
                options: ["Hydrogen bonding", 
                        "Dipole-dipole forces", 
                        "Dispersion forces", 
                        "Ionic interactions"],
                correctAnswer: 2,
            },
            {
                question: "Why does SiO2 have a very high melting point?",
                options: ["It is held together by weak dispersion forces", 
                        "It has strong covalent bonds in a 3D lattice", 
                        "It contains metallic bonding", 
                        "It is a polar molecule"],
                correctAnswer: 1,
            },
            {
                question: "Which of these molecules is trigonal pyramidal in shape?",
                options: ["NH3", 
                        "CH4", 
                        "CO2", 
                        "BF3"],
                correctAnswer: 0,
            },
        ],
    },

    {
        category: "2.5 organic chemistry",
        questions: [
            {
                question: "What is the functional group in alcohols?",
                options: ["-COOH", 
                        "-OH", 
                        "-NH2", 
                        "-C=O"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following is a structural isomer of butane (C4H10)?",
                options: ["Methane", 
                        "2-methylpropane", 
                        "Pentane", 
                        "Ethene"],
                correctAnswer: 1,
            },
            {
                question: "What type of reaction converts an alkene into an alkane?",
                options: ["Substitution", 
                        "Elimination", 
                        "Hydrogenation (addition)", 
                        "Oxidation"],
                correctAnswer: 2,
            },
            {
                question: "Which reagent is used to test for alkenes?",
                options: ["Acidified dichromate", 
                        "Bromine water", 
                        "Universal indicator", 
                        "Silver nitrate"],
                correctAnswer: 1,
            },
            {
                question: "What is the product when ethanol is oxidised using acidified dichromate?",
                options: ["Ethane", 
                        "Ethanoic acid", 
                        "Ethene", 
                        "Methanol"],
                correctAnswer: 1,
            },
            {
                question: "Which compound has the functional group -COOH?",
                options: ["Alcohol", 
                        "Carboxylic acid", 
                        "Ketone", 
                        "Amine"],
                correctAnswer: 1,
            },
            {
                question: "Which of these is the correct name for CH3CH2CH2OH?",
                options: ["Methanol", 
                        "Ethanol", 
                        "Propanol", 
                        "Butanol"],
                correctAnswer: 2,
            },
            {
                question: "What type of reaction is the conversion of an alcohol to a haloalkane?",
                options: ["Substitution", 
                        "Addition", 
                        "Elimination", 
                        "Oxidation"],
                correctAnswer: 0,
            },
            {
                question: "What is the molecular formula of ethanoic acid?",
                options: ["CH3CHO", 
                        "C2H5OH", 
                        "CH3COOH", 
                        "C2H6"],
                correctAnswer: 2,
            },
            {
                question: "What is the major product when 2-bromopropane reacts with aqueous NaOH?",
                options: ["Propene", 
                        "Propan-2-ol", 
                        "Propanone", 
                        "Butane"],
                correctAnswer: 1,
            },
            {
                question: "What happens to bromine water when it reacts with an alkene?",
                options: ["It turns colourless", 
                        "It stays orange", 
                        "It turns purple", 
                        "It forms a precipitate"],
                correctAnswer: 0,
            },
            {
                question: "What type of bonding occurs in alkanes?",
                options: ["Double covalent bonds", 
                        "Single covalent bonds only", 
                        "Hydrogen bonds", 
                        "Ionic bonds"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following is a secondary alcohol?",
                options: ["Propan-1-ol", 
                        "Propan-2-ol", 
                        "Methanol", 
                        "Ethanol"],
                correctAnswer: 1,
            },
            {
                question: "What is formed when an alcohol reacts with a carboxylic acid under reflux with concentrated H2SO4?",
                options: ["Ester", 
                        "Ketone", 
                        "Aldehyde", 
                        "Alkene"],
                correctAnswer: 0,
            },
            {
                question: "Which compound is produced when propene reacts with HBr?",
                options: ["1-bromopropane", 
                        "2-bromopropane", 
                        "Propan-2-ol", 
                        "Propanal"],
                correctAnswer: 1,
            },
            {
                question: "What type of isomerism exists between but-1-ene and but-2-ene?",
                options: ["Chain isomerism", 
                        "Geometric isomerism", 
                        "Position isomerism", 
                        "Functional group isomerism"],
                correctAnswer: 2,
            },
            {
                question: "Which of the following shows geometric (cis/trans) isomerism?",
                options: ["Propene", 
                        "But-2-ene", 
                        "Ethane", 
                        "Methanol"],
                correctAnswer: 1,
            },
            {
                question: "What type of reaction occurs when an alkene reacts with water in the presence of H+ catalyst?",
                options: ["Hydration (addition)", 
                        "Dehydration (elimination)", 
                        "Substitution", 
                        "Oxidation"],
                correctAnswer: 0,
            },
            {
                question: "Why do alcohols have higher boiling points than alkanes of similar molar mass?",
                options: ["They are polar molecules and can hydrogen bond", 
                        "They have stronger dispersion forces only", 
                        "They contain double bonds", 
                        "They have ionic bonding"],
                correctAnswer: 0,
            },
            {
                question: "What product is formed when butan-2-ol is oxidised under reflux with acidified dichromate?",
                options: ["Butanal", 
                        "Butanoic acid", 
                        "Butanone", 
                        "Butene"],
                correctAnswer: 2,
            },
            {
                question: "What type of polymer is formed from alkenes?",
                options: ["Addition polymer", 
                        "Condensation polymer", 
                        "Ionic polymer", 
                        "Hydrogen-bonded polymer"],
                correctAnswer: 0,
            },
            {
                question: "What is the main product when ethanol undergoes dehydration with concentrated H2SO4?",
                options: ["Ethanoic acid", 
                        "Ethene", 
                        "Ethanone", 
                        "Ethyl ethanoate"],
                correctAnswer: 1,
            },
            {
                question: "Which reagent is used to distinguish between primary, secondary, and tertiary alcohols?",
                options: ["Bromine water", 
                        "Tollens' reagent", 
                        "Acidified dichromate", 
                        "Universal indicator"],
                correctAnswer: 2,
            },
            {
                question: "Which of the following is the correct IUPAC name for CH3CHBrCH3?",
                options: ["1-bromopropane", 
                        "2-bromopropane", 
                        "3-bromopropane", 
                        "Bromomethane"],
                correctAnswer: 1,
            },
            {
                question: "What type of reaction is the conversion of an alcohol into an alkene?",
                options: ["Substitution", 
                        "Oxidation", 
                        "Elimination (dehydration)", 
                        "Addition"],
                correctAnswer: 2,
            },
        ],
    },

    {
        category: "2.6 chemical reactivity",
        questions: [
            {
                question: "According to collision theory, what must particles have for a reaction to occur?",
                options: ["High concentration only", 
                        "Correct orientation only", 
                        "Sufficient energy and correct orientation", 
                        "Catalysts present"],
                correctAnswer: 2,
            },
            {
                question: "What effect does increasing temperature have on the rate of a chemical reaction?",
                options: ["Decreases rate", 
                        "Increases rate due to more frequent and energetic collisions", 
                        "Has no effect", 
                        "Stops the reaction completely"],
                correctAnswer: 1,
            },
            {
                question: "What is the role of a catalyst in a reaction?",
                options: ["Increases equilibrium yield", 
                        "Provides an alternative pathway with lower activation energy", 
                        "Increases temperature of the reaction", 
                        "Changes the position of equilibrium"],
                correctAnswer: 1,
            },
            {
                question: "Which factor does NOT affect the rate of a chemical reaction?",
                options: ["Surface area", 
                        "Concentration", 
                        "Catalyst", 
                        "Colour of the reactants"],
                correctAnswer: 3,
            },
            {
                question: "What happens to the equilibrium position if the concentration of a reactant is increased?",
                options: ["Shifts to the left", 
                        "Shifts to the right", 
                        "Stays the same", 
                        "Reaction stops"],
                correctAnswer: 1,
            },
            {
                question: "Which change will shift the equilibrium position to favour the products in an exothermic reaction?",
                options: ["Decrease temperature", 
                        "Increase temperature", 
                        "Add a catalyst", 
                        "Remove products"],
                correctAnswer: 0,
            },
            {
                question: "At equilibrium, the concentrations of reactants and products:",
                options: ["Are equal", 
                        "Are constant", 
                        "Keep changing", 
                        "Are always greater for products"],
                correctAnswer: 1,
            },
            {
                question: "What happens to the rate of reaction if the surface area of a solid reactant is increased?",
                options: ["Increases", 
                        "Decreases", 
                        "No change", 
                        "Stops completely"],
                correctAnswer: 0,
            },
            {
                question: "For the equilibrium reaction N2(g) + 3H2(g) ⇌ 2NH3(g), what happens if pressure is increased?",
                options: ["Equilibrium shifts to the left", 
                        "Equilibrium shifts to the right", 
                        "No change", 
                        "Reaction stops"],
                correctAnswer: 1,
            },
            {
                question: "What does the equilibrium constant (Kc) depend on?",
                options: ["Temperature only", 
                        "Concentration only", 
                        "Pressure only", 
                        "Catalyst only"],
                correctAnswer: 0,
            },
            {
                question: "What effect does a catalyst have on the position of equilibrium?",
                options: ["Shifts it to the right", 
                        "Shifts it to the left", 
                        "No effect on position, only reached faster", 
                        "Increases Kc"],
                correctAnswer: 2,
            },
            {
                question: "Which factor increases the frequency of collisions between particles?",
                options: ["Lowering concentration", 
                        "Increasing concentration", 
                        "Using a catalyst", 
                        "Decreasing surface area"],
                correctAnswer: 1,
            },
            {
                question: "Why does increasing temperature increase the rate of reaction?",
                options: ["More particles collide with correct orientation", 
                        "More particles have energy greater than activation energy", 
                        "Catalyst works better", 
                        "Concentration increases"],
                correctAnswer: 1,
            },
            {
                question: "What type of system is required for equilibrium to be established?",
                options: ["Open system", 
                        "Closed system", 
                        "System with catalyst", 
                        "System at high pressure"],
                correctAnswer: 1,
            },
            {
                question: "What effect does removing products have on an equilibrium system?",
                options: ["Shifts equilibrium to the right", 
                        "Shifts equilibrium to the left", 
                        "No effect", 
                        "Decreases rate"],
                correctAnswer: 0,
            },
            {
                question: "Which of the following statements about equilibrium is correct?",
                options: ["Forward and reverse reactions stop", 
                        "Forward and reverse reactions continue at the same rate", 
                        "Products are no longer formed", 
                        "Reactants are completely used up"],
                correctAnswer: 1,
            },
            {
                question: "What happens to the rate of reaction when a catalyst is added?",
                options: ["Rate decreases", 
                        "Rate increases", 
                        "No effect", 
                        "Reaction stops"],
                correctAnswer: 1,
            },
            {
                question: "For an endothermic reaction, what effect does increasing temperature have?",
                options: ["Shifts equilibrium to the left", 
                        "Shifts equilibrium to the right", 
                        "Decreases reaction rate", 
                        "No effect"],
                correctAnswer: 1,
            },
            {
                question: "Why does increasing concentration of reactants increase reaction rate?",
                options: ["Particles have less energy", 
                        "Particles collide more frequently", 
                        "Activation energy increases", 
                        "Catalyst forms"],
                correctAnswer: 1,
            },
            {
                question: "If a reversible reaction has Kc > 1, what does this mean?",
                options: ["Reactants are favoured", 
                        "Products are favoured", 
                        "Reaction is not at equilibrium", 
                        "Reaction is endothermic"],
                correctAnswer: 1,
            },
            {
                question: "What happens to Kc when a catalyst is added?",
                options: ["Increases", 
                        "Decreases", 
                        "No change", 
                        "Becomes zero"],
                correctAnswer: 2,
            },
            {
                question: "Which factor affects both the rate of reaction and equilibrium position?",
                options: ["Catalyst", 
                        "Temperature", 
                        "Pressure", 
                        "Surface area"],
                correctAnswer: 1,
            },
            {
                question: "Why does increasing surface area increase reaction rate for solids?",
                options: ["It increases activation energy", 
                        "It increases number of collisions", 
                        "It decreases concentration", 
                        "It decreases pressure"],
                correctAnswer: 1,
            },
            {
                question: "What effect does decreasing pressure have on the equilibrium involving gases?",
                options: ["Favours the side with more moles of gas", 
                        "Favours the side with fewer moles of gas", 
                        "Has no effect", 
                        "Stops the reaction"],
                correctAnswer: 0,
            },
            {
                question: "At equilibrium, which of the following is true?",
                options: ["Forward and reverse rates are equal", 
                        "Concentrations of reactants and products are equal", 
                        "Forward reaction stops", 
                        "System contains only products"],
                correctAnswer: 0,
            },
        ],
    },

    {
        category: "2.7 oxidation-reduction chemistry",
        questions: [
            {
                question: "What is the definition of oxidation in terms of electrons?",
                options: ["Loss of electrons", 
                        "Gain of electrons", 
                        "Sharing of electrons", 
                        "No change in electrons"],
                correctAnswer: 0,
            },
            {
                question: "What is the oxidation number of oxygen in H2O?",
                options: ["-1", 
                        "0", 
                        "-2", 
                        "+2"],
                correctAnswer: 2,
            },
            {
                question: "Which species is oxidised in the reaction: Zn + Cu2+ → Zn2+ + Cu?",
                options: ["Zn", 
                        "Cu2+", 
                        "Cu", 
                        "H2O"],
                correctAnswer: 0,
            },
            {
                question: "In the same reaction, which species is reduced: Zn + Cu2+ → Zn2+ + Cu?",
                options: ["Zn", 
                        "Cu2+", 
                        "Zn2+", 
                        "O2"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following is the strongest reducing agent?",
                options: ["Mg", 
                        "Fe2+", 
                        "Ag", 
                        "Cu2+"],
                correctAnswer: 0,
            },
            {
                question: "What is the oxidation number of sulfur in SO2?",
                options: ["+2", 
                        "+4", 
                        "-2", 
                        "+6"],
                correctAnswer: 1,
            },
            {
                question: "Which metal will displace copper from a solution of CuSO4?",
                options: ["Ag", 
                        "Au", 
                        "Mg", 
                        "Hg"],
                correctAnswer: 2,
            },
            {
                question: "What is the oxidising agent in the reaction: 2Fe3+ + Zn → 2Fe2+ + Zn2+?",
                options: ["Fe3+", 
                        "Fe2+", 
                        "Zn", 
                        "Zn2+"],
                correctAnswer: 0,
            },
            {
                question: "What is the reducing agent in the same reaction: 2Fe3+ + Zn → 2Fe2+ + Zn2+?",
                options: ["Fe3+", 
                        "Zn", 
                        "Fe2+", 
                        "Zn2+"],
                correctAnswer: 1,
            },
            {
                question: "What is the oxidation number of chlorine in Cl2?",
                options: ["-1", 
                        "0", 
                        "+1", 
                        "-2"],
                correctAnswer: 1,
            },
            {
                question: "Which half-equation represents reduction?",
                options: ["Zn → Zn2+ + 2e-", 
                        "Cl2 + 2e- → 2Cl-", 
                        "Mg → Mg2+ + 2e-", 
                        "Fe2+ → Fe3+ + e-"],
                correctAnswer: 1,
            },
            {
                question: "Which statement about redox reactions is correct?",
                options: ["Oxidation and reduction occur separately", 
                        "Oxidation and reduction always occur together", 
                        "Only metals can be oxidised", 
                        "Only non-metals can be reduced"],
                correctAnswer: 1,
            },
            {
                question: "What is the oxidation number of nitrogen in NO30-?",
                options: ["+5", 
                        "+3", 
                        "-1", 
                        "+4"],
                correctAnswer: 0,
            },
            {
                question: "In acidic solution, which species is formed when MnO4- is reduced?",
                options: ["Mn2+", 
                        "MnO2", 
                        "Mn", 
                        "Mn3+"],
                correctAnswer: 0,
            },
            {
                question: "Which equation shows a displacement reaction?",
                options: ["Cu + Zn2+ → Cu2+ + Zn", 
                        "Zn + Cu2+ → Zn2+ + Cu", 
                        "NaCl → Na+ + Cl-", 
                        "H2O → H2 + O2"],
                correctAnswer: 1,
            },
            {
                question: "What is the oxidation number of carbon in CO2?",
                options: ["0", 
                        "+2", 
                        "+4", 
                        "-4"],
                correctAnswer: 2,
            },
            {
                question: "Which element is always assigned an oxidation number of -1 in compounds?",
                options: ["Oxygen", 
                        "Hydrogen", 
                        "Chlorine", 
                        "Fluorine"],
                correctAnswer: 3,
            },
            {
                question: "Which of the following is an example of a redox reaction?",
                options: ["NaCl dissolving in water", 
                        "H2 + Cl2 → 2HCl", 
                        "Mixing ethanol and water", 
                        "Heating NaCl"],
                correctAnswer: 1,
            },
            {
                question: "Which of these species acts as an oxidising agent?",
                options: ["Zn", 
                        "Cl2", 
                        "Fe2+", 
                        "Mg"],
                correctAnswer: 1,
            },
            {
                question: "What happens to the oxidation number of an element that is oxidised?",
                options: ["It decreases", 
                        "It increases", 
                        "It stays the same", 
                        "It becomes zero"],
                correctAnswer: 1,
            },
            {
                question: "In an electrochemical cell, which electrode is the site of oxidation?",
                options: ["Cathode", 
                        "Anode", 
                        "Both electrodes", 
                        "Neither electrode"],
                correctAnswer: 1,
            },
            {
                question: "In the same cell, which electrode is the site of reduction?",
                options: ["Cathode", 
                        "Anode", 
                        "Both electrodes", 
                        "Neither electrode"],
                correctAnswer: 0,
            },
            {
                question: "Which of these metals is least reactive based on the activity series?",
                options: ["Mg", 
                        "Zn", 
                        "Ag", 
                        "Fe"],
                correctAnswer: 2,
            },
            {
                question: "What is the change in oxidation number of Mn in MnO4- to Mn2+?",
                options: ["+7 to +2", 
                        "+4 to +2", 
                        "+6 to +2", 
                        "+5 to +3"],
                correctAnswer: 0,
            },
            {
                question: "Which reaction demonstrates the reactivity of halogens?",
                options: ["Cl2 + 2NaBr → 2NaCl + Br2", 
                        "NaCl → Na + Cl2", 
                        "H2O → H2 + O2", 
                        "C + O2 → CO2"],
                correctAnswer: 0,
            },
        ]
    }
]