// Questions sorted by category (25 each)
// Question content is copied using AI, the coding format and main array is created by me
const questions = [
    {
        category: "2.1 physics investigation",
        questions: [
            {
                question: "What is the purpose of repeating measurements in a physics investigation?",
                options: ["To increase systematic error", 
                        "To reduce random error", 
                        "To make results less accurate", 
                        "To avoid using a graph"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following best describes a dependent variable?",
                options: ["The variable you change", 
                        "The variable you keep constant", 
                        "The variable you measure", 
                        "The variable that has no effect"],
                correctAnswer: 2,
            },
            {
                question: "Which unit is used to measure acceleration?",
                options: ["m/s", 
                        "m/s²", 
                        "N", 
                        "J"],
                correctAnswer: 1,
            },
            {
                question: "A student measures the period of a pendulum. Which instrument would be most appropriate?",
                options: ["Metre ruler", 
                        "Protractor", 
                        "Stopwatch", 
                        "Spring balance"],
                correctAnswer: 2,
            },
            {
                question: "When plotting a graph, which variable goes on the x-axis?",
                options: ["Dependent variable", 
                        "Independent variable", 
                        "Control variable", 
                        "Uncertainty"],
                correctAnswer: 1,
            },
            {
                question: "What does a straight-line graph through the origin indicate about two variables?",
                options: ["They are unrelated", 
                        "They are inversely proportional", 
                        "They are directly proportional", 
                        "One is constant"],
                correctAnswer: 2,
            },
            {
                question: "The slope of a velocity-time graph represents:",
                options: ["Displacement", 
                        "Acceleration", 
                        "Velocity", 
                        "Force"],
                correctAnswer: 1,
            },
            {
                question: "Which factor contributes to systematic error?",
                options: ["Parallax error when reading a scale", 
                        "A stopwatch running slow", 
                        "Random fluctuations in measurements", 
                        "Repeating trials"],
                correctAnswer: 1,
            },
            {
                question: "How can random error be reduced in an investigation?",
                options: ["Calibrating instruments", 
                        "Repeating measurements", 
                        "Changing the hypothesis", 
                        "Ignoring outliers"],
                correctAnswer: 1,
            },
            {
                question: "What is the SI unit for force?",
                options: ["Joule", 
                        "Newton", 
                        "Watt", 
                        "Pascal"],
                correctAnswer: 1,
            },
            {
                question: "Which piece of equipment measures electrical current?",
                options: ["Voltmeter", 
                        "Ammeter", 
                        "Ohmmeter", 
                        "Thermometer"],
                correctAnswer: 1,
            },
            {
                question: "What must be kept constant in a fair test?",
                options: ["Only the dependent variable", 
                        "Independent and dependent variables", 
                        "Control variables", 
                        "All variables"],
                correctAnswer: 2,
            },
            {
                question: "Which graph would you use to determine the spring constant, k, from Hooke’s Law?",
                options: ["Force vs. extension", 
                        "Extension vs. time", 
                        "Mass vs. volume", 
                        "Force vs. velocity"],
                correctAnswer: 0,
            },
            {
                question: "The area under a force-displacement graph represents:",
                options: ["Velocity", 
                        "Kinetic energy", 
                        "Work done", 
                        "Power"],
                correctAnswer: 2,
            },
            {
                question: "Why is a line of best fit drawn on a scatter graph?",
                options: ["To ignore anomalies", 
                        "To show the average trend", 
                        "To prove the hypothesis", 
                        "To remove errors"],
                correctAnswer: 1,
            },
            {
                question: "Which of these increases the reliability of an experiment?",
                options: ["Repeating the experiment and averaging results", 
                        "Using one set of data only", 
                        "Ignoring outliers", 
                        "Shortening the experiment"],
                correctAnswer: 0,
            },
            {
                question: "If a graph has the form y = kx, the gradient represents:",
                options: ["The dependent variable", 
                        "The control variable", 
                        "The proportionality constant", 
                        "Random error"],
                correctAnswer: 2,
            },
            {
                question: "Why should you record raw data with appropriate significant figures?",
                options: ["To match the precision of the measuring instrument", 
                        "To make numbers easier", 
                        "To reduce systematic error", 
                        "To make graphs simpler"],
                correctAnswer: 0,
            },
            {
                question: "A student investigates Ohm's Law. Which graph should be plotted to find resistance?",
                options: ["Current vs. time", 
                        "Voltage vs. current", 
                        "Resistance vs. voltage", 
                        "Power vs. current"],
                correctAnswer: 1,
            },
            {
                question: "The intercept of a velocity-time graph represents:",
                options: ["Acceleration", 
                        "Initial velocity", 
                        "Displacement", 
                        "Final velocity"],
                correctAnswer: 1,
            },
            {
                question: "Why is it important to identify uncertainties in a physics investigation?",
                options: ["To reduce accuracy", 
                        "To estimate reliability of results", 
                        "To prove the hypothesis is correct", 
                        "To remove systematic error"],
                correctAnswer: 1,
            },
            {
                question: "In an experiment to measure acceleration due to gravity using a falling object, which factor must be minimised?",
                options: ["Air resistance", 
                        "Mass of the object", 
                        "Gravitational field strength", 
                        "Initial height"],
                correctAnswer: 0,
            },
            {
                question: "What does a curved line on a displacement-time graph represent?",
                options: ["Constant speed", 
                        "Acceleration", 
                        "Rest", 
                        "Negative velocity"],
                correctAnswer: 1,
            },
            {
                question: "What is the SI unit for power?",
                options: ["Newton", 
                        "Joule", 
                        "Watt", 
                        "Pascal"],
                correctAnswer: 2,
            },
            {
                question: "When drawing a conclusion, it must be based on:",
                options: ["The hypothesis only", 
                        "The data collected", 
                        "What was expected", 
                        "Previous experiments"],
                correctAnswer: 1,
            },
        ],
    },

    {
        category: "2.3 waves",
        questions: [
            {
                question: "What type of wave requires a medium to travel through?",
                options: ["Electromagnetic wave", 
                        "Sound wave", 
                        "Light wave", 
                        "Gamma ray"],
                correctAnswer: 1,
            },
            {
                question: "Which quantity is measured in Hertz (Hz)?",
                options: ["Wavelength", 
                        "Amplitude", 
                        "Frequency", 
                        "Speed"],
                correctAnswer: 2,
            },
            {
                question: "The speed of a wave can be calculated using which equation?",
                options: ["v = f x λ", 
                        "v = f / λ", 
                        "v = λ / f", 
                        "v = a x t"],
                correctAnswer: 0,
            },
            {
                question: "When a wave passes from deep water to shallow water, it:",
                options: ["Speeds up and bends away from the normal", 
                        "Slows down and bends towards the normal", 
                        "Slows down and bends away from the normal", 
                        "Speeds up and bends towards the normal"],
                correctAnswer: 1,
            },
            {
                question: "Which term describes the maximum displacement of a wave from its equilibrium position?",
                options: ["Frequency", 
                        "Amplitude", 
                        "Wavelength", 
                        "Period"],
                correctAnswer: 1,
            },
            {
                question: "The time for one full wave to pass a point is called the:",
                options: ["Wavelength", 
                        "Period", 
                        "Frequency", 
                        "Phase"],
                correctAnswer: 1,
            },
            {
                question: "What is diffraction?",
                options: ["The bending of waves around an obstacle", 
                        "The spreading of light into colours", 
                        "The bouncing of waves off a surface", 
                        "The overlapping of two waves"],
                correctAnswer: 0,
            },
            {
                question: "Which condition is required for significant diffraction of waves?",
                options: ["Large wavelength compared to gap size", 
                        "Small wavelength compared to gap size", 
                        "High frequency waves", 
                        "Low amplitude waves"],
                correctAnswer: 0,
            },
            {
                question: "Constructive interference occurs when:",
                options: ["Two crests overlap", 
                        "A crest and trough overlap", 
                        "Two troughs overlap destructively", 
                        "Waves pass through each other unchanged"],
                correctAnswer: 0,
            },
            {
                question: "In destructive interference, the waves:",
                options: ["Add together to increase amplitude", 
                        "Cancel out partially or completely", 
                        "Pass through each other unchanged", 
                        "Reflect off a boundary"],
                correctAnswer: 1,
            },
            {
                question: "Standing waves form due to:",
                options: ["Reflection and interference of waves", 
                        "Diffraction of waves at an edge", 
                        "Only constructive interference", 
                        "Absorption of energy"],
                correctAnswer: 0,
            },
            {
                question: "Nodes in a standing wave are points of:",
                options: ["Maximum amplitude", 
                        "Zero displacement", 
                        "Maximum frequency", 
                        "Constant velocity"],
                correctAnswer: 1,
            },
            {
                question: "Antinodes in a standing wave are points of:",
                options: ["Zero displacement", 
                        "Minimum frequency", 
                        "Maximum amplitude", 
                        "Constant speed"],
                correctAnswer: 2,
            },
            {
                question: "Which of the following is a transverse wave?",
                options: ["Sound", 
                        "Light", 
                        "Seismic P-wave", 
                        "Ultrasound"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following is a longitudinal wave?",
                options: ["Light", 
                        "Radio", 
                        "Sound", 
                        "Microwaves"],
                correctAnswer: 2,
            },
            {
                question: "The bending of light as it enters a new medium is called:",
                options: ["Diffraction", 
                        "Reflection", 
                        "Refraction", 
                        "Interference"],
                correctAnswer: 2,
            },
            {
                question: "The law of reflection states that:",
                options: ["Angle of incidence = angle of refraction", 
                        "Angle of incidence = angle of reflection", 
                        "Wavelength in air = wavelength in water", 
                        "Frequency changes when waves reflect"],
                correctAnswer: 1,
            },
            {
                question: "In refraction, which property of a wave remains constant?",
                options: ["Speed", 
                        "Wavelength", 
                        "Frequency", 
                        "Direction"],
                correctAnswer: 2,
            },
            {
                question: "Resonance occurs when:",
                options: ["A system is forced at its natural frequency", 
                        "Waves cancel each other completely", 
                        "Light is refracted through a prism", 
                        "A wave bends around an obstacle"],
                correctAnswer: 0,
            },
            {
                question: "The Doppler effect is a change in:",
                options: ["Wavelength due to interference", 
                        "Amplitude due to resonance", 
                        "Frequency due to relative motion", 
                        "Speed due to reflection"],
                correctAnswer: 2,
            },
            {
                question: "Which colour of visible light has the shortest wavelength?",
                options: ["Red", 
                        "Yellow", 
                        "Green", 
                        "Violet"],
                correctAnswer: 3,
            },
            {
                question: "What is the relationship between frequency and wavelength of a wave at constant speed?",
                options: ["Directly proportional", 
                        "Inversely proportional", 
                        "No relationship", 
                        "Both increase together"],
                correctAnswer: 1,
            },
            {
                question: "Two sources produce waves of the same frequency and amplitude that arrive in phase. The result is:",
                options: ["Destructive interference", 
                        "Constructive interference", 
                        "No interference", 
                        "Resonance"],
                correctAnswer: 1,
            },
            {
                question: "If the frequency of a wave doubles while speed stays constant, its wavelength:",
                options: ["Doubles", 
                        "Halves", 
                        "Stays the same", 
                        "Becomes zero"],
                correctAnswer: 1,
            },
            {
                question: "In a double-slit experiment, bright fringes occur due to:",
                options: ["Reflection", 
                        "Constructive interference", 
                        "Destructive interference", 
                        "Diffraction only"],
                correctAnswer: 1,
            },
        ],
    },

    {
        category: "2.4 mechanics",
        questions: [
            {
                question: "Which equation links acceleration, change in velocity, and time?",
                options: ["a = v / t", 
                        "a = Δv / t", 
                        "a = F / m", 
                        "a = s / t"],
                correctAnswer: 1,
            },
            {
                question: "What is the SI unit of force?",
                options: ["Joule", 
                        "Newton", 
                        "Pascal", 
                        "Watt"],
                correctAnswer: 1,
            },
            {
                question: "Which law states that an object will remain at rest or in uniform motion unless acted upon by an external force?",
                options: ["Newton's First Law", 
                        "Newton's Second Law", 
                        "Newton's Third Law", 
                        "Law of Gravitation"],
                correctAnswer: 0,
            },
            {
                question: "What is the acceleration due to gravity on Earth approximately?",
                options: ["1.6 m/s²", 
                        "5.0 m/s²", 
                        "9.8 m/s²", 
                        "12 m/s²"],
                correctAnswer: 2,
            },
            {
                question: "Which quantity is defined as mass x velocity?",
                options: ["Force", 
                        "Acceleration", 
                        "Momentum", 
                        "Impulse"],
                correctAnswer: 2,
            },
            {
                question: "What is the unit of momentum?",
                options: ["kg·m/s", 
                        "N·m", 
                        "J", 
                        "W"],
                correctAnswer: 0,
            },
            {
                question: "When two objects collide and stick together, the collision is:",
                options: ["Elastic", 
                        "Inelastic", 
                        "Perfectly elastic", 
                        "Non-collisional"],
                correctAnswer: 1,
            },
            {
                question: "Which principle states that momentum is conserved when no external force acts?",
                options: ["Conservation of Energy", 
                        "Conservation of Momentum", 
                        "Newton's First Law", 
                        "Work-Energy Principle"],
                correctAnswer: 1,
            },
            {
                question: "Which equation defines kinetic energy?",
                options: ["KE = mv", 
                        "KE = ½mv²", 
                        "KE = mgh", 
                        "KE = Fd"],
                correctAnswer: 1,
            },
            {
                question: "What is the unit of work?",
                options: ["Watt", 
                        "Newton", 
                        "Joule", 
                        "Pascal"],
                correctAnswer: 2,
            },
            {
                question: "What is the condition for an object to be in equilibrium?",
                options: ["Resultant force is not zero", 
                        "Resultant force is zero", 
                        "Acceleration is constant", 
                        "Velocity is zero"],
                correctAnswer: 1,
            },
            {
                question: "What force provides the centripetal force for a car turning on a flat road?",
                options: ["Weight", 
                        "Normal force", 
                        "Friction", 
                        "Air resistance"],
                correctAnswer: 2,
            },
            {
                question: "Which equation gives the centripetal force?",
                options: ["Fc = mv", 
                        "Fc = mv² / r", 
                        "Fc = Fd", 
                        "Fc = ma / r"],
                correctAnswer: 1,
            },
            {
                question: "Which force balances the weight of an object at rest on a flat surface?",
                options: ["Friction", 
                        "Normal force", 
                        "Tension", 
                        "Air resistance"],
                correctAnswer: 1,
            },
            {
                question: "What is the weight of a 2.0 kg mass on Earth?",
                options: ["2.0 N", 
                        "9.8 N", 
                        "19.6 N", 
                        "98 N"],
                correctAnswer: 2,
            },
            {
                question: "Which energy transformation occurs when an object falls freely?",
                options: ["Kinetic → Potential", 
                        "Potential → Kinetic", 
                        "Heat → Potential", 
                        "Elastic → Kinetic"],
                correctAnswer: 1,
            },
            {
                question: "Impulse is equal to:",
                options: ["Force x distance", 
                        "Change in velocity", 
                        "Change in momentum", 
                        "Kinetic energy"],
                correctAnswer: 2,
            },
            {
                question: "What is the SI unit of power?",
                options: ["Watt", 
                        "Joule", 
                        "Newton", 
                        "Pascal"],
                correctAnswer: 0,
            },
            {
                question: "If net force on an object is zero, its velocity will:",
                options: ["Increase", 
                        "Decrease", 
                        "Stay constant", 
                        "Become zero"],
                correctAnswer: 2,
            },
            {
                question: "The slope of a displacement-time graph represents:",
                options: ["Displacement", 
                        "Acceleration", 
                        "Velocity", 
                        "Force"],
                correctAnswer: 2,
            },
            {
                question: "The slope of a velocity-time graph represents:",
                options: ["Displacement", 
                        "Acceleration", 
                        "Force", 
                        "Momentum"],
                correctAnswer: 1,
            },
            {
                question: "The area under a velocity-time graph represents:",
                options: ["Acceleration", 
                        "Displacement", 
                        "Force", 
                        "Momentum"],
                correctAnswer: 1,
            },
            {
                question: "What happens to centripetal force if the speed of an object doubles?",
                options: ["It halves", 
                        "It doubles", 
                        "It quadruples", 
                        "It stays the same"],
                correctAnswer: 2,
            },
            {
                question: "Which statement about kinetic and potential energy is correct in a closed system?",
                options: ["Kinetic energy is always constant", 
                        "Potential energy is always constant", 
                        "Total mechanical energy is conserved", 
                        "Energy is lost to the system"],
                correctAnswer: 2,
            },
            {
                question: "Which of Newton's laws explains why passengers move forward when a car suddenly stops?",
                options: ["First Law", 
                        "Second Law", 
                        "Third Law", 
                        "Law of Gravitation"],
                correctAnswer: 0,
            },
        ],
    },

    {
        category: "2.5 atomic physics",
        questions: [
            {
                question: "Which particle has a positive charge?",
                options: ["Proton", 
                        "Neutron", 
                        "Electron", 
                        "Gamma ray"],
                correctAnswer: 0,
            },
            {
                question: "Which radiation has the greatest penetrating ability?",
                options: ["Alpha", 
                        "Beta", 
                        "Gamma", 
                        "Neutron"],
                correctAnswer: 2,
            },
            {
                question: "Which radiation is stopped by a sheet of paper?",
                options: ["Alpha", 
                        "Beta", 
                        "Gamma", 
                        "Neutron"],
                correctAnswer: 0,
            },
            {
                question: "What does the atomic number of an element represent?",
                options: ["Number of neutrons", 
                        "Number of protons", 
                        "Number of nucleons", 
                        "Mass number"],
                correctAnswer: 1,
            },
            {
                question: "Which of the following is an isotope of carbon?",
                options: ["14N", 
                        "14C", 
                        "13N", 
                        "12B"],
                correctAnswer: 1,
            },
            {
                question: "What is emitted in beta-minus decay?",
                options: ["A neutron", 
                        "A proton", 
                        "An electron", 
                        "A helium nucleus"],
                correctAnswer: 2,
            },
            {
                question: "Which of these is a property of gamma radiation?",
                options: ["High ionising ability", 
                        "Deflected by electric fields", 
                        "No mass and no charge", 
                        "Stopped by paper"],
                correctAnswer: 2,
            },
            {
                question: "What is the mass number of an atom?",
                options: ["Number of electrons", 
                        "Number of protons and neutrons", 
                        "Number of protons", 
                        "Number of neutrons only"],
                correctAnswer: 1,
            },
            {
                question: "During alpha decay, the mass number of the nucleus decreases by:",
                options: ["1", 
                        "2", 
                        "3", 
                        "4"],
                correctAnswer: 3,
            },
            {
                question: "During beta-minus decay, a neutron changes into:",
                options: ["A proton and an electron", 
                        "A neutron and a proton", 
                        "An electron and gamma ray", 
                        "A proton only"],
                correctAnswer: 0,
            },
            {
                question: "The half-life of a radioactive isotope is the time taken for:",
                options: ["All atoms to decay", 
                        "Half the atoms to decay", 
                        "The activity to double", 
                        "Neutrons to stop emitting"],
                correctAnswer: 1,
            },
            {
                question: "If a sample has a half-life of 10 minutes, how much remains after 20 minutes?",
                options: ["All", 
                        "Three-quarters", 
                        "One-quarter", 
                        "One-half"],
                correctAnswer: 2,
            },
            {
                question: "Which of these is a use of radioactive isotopes?",
                options: ["Measuring current", 
                        "Carbon dating", 
                        "Producing sound waves", 
                        "Generating electricity directly"],
                correctAnswer: 1,
            },
            {
                question: "Which force holds protons and neutrons together in the nucleus?",
                options: ["Gravitational force", 
                        "Electrostatic force", 
                        "Strong nuclear force", 
                        "Weak nuclear force"],
                correctAnswer: 2,
            },
            {
                question: "Which type of radiation is used in smoke detectors?",
                options: ["Gamma", 
                        "Alpha", 
                        "Beta", 
                        "Neutrons"],
                correctAnswer: 1,
            },
            {
                question: "What happens to the atomic number after beta-minus decay?",
                options: ["Decreases by 1", 
                        "Increases by 1", 
                        "Stays the same", 
                        "Decreases by 2"],
                correctAnswer: 1,
            },
            {
                question: "What is the charge of a neutron?",
                options: ["Positive", 
                        "Negative", 
                        "Zero", 
                        "Double positive"],
                correctAnswer: 2,
            },
            {
                question: "In nuclear fission, a large nucleus:",
                options: ["Joins with another nucleus", 
                        "Splits into smaller nuclei", 
                        "Releases electrons", 
                        "Absorbs gamma radiation"],
                correctAnswer: 1,
            },
            {
                question: "Which radiation is deflected the most in an electric field?",
                options: ["Alpha", 
                        "Beta", 
                        "Gamma", 
                        "Neutron"],
                correctAnswer: 1,
            },
            {
                question: "What is the main danger of ionising radiation to living tissue?",
                options: ["Causes vibrations", 
                        "Causes mutations and cell damage", 
                        "Causes heating only", 
                        "Changes colour of skin"],
                correctAnswer: 1,
            },
            {
                question: "Which particle is emitted during positron (beta-plus) decay?",
                options: ["Electron", 
                        "Proton", 
                        "Positron", 
                        "Alpha particle"],
                correctAnswer: 2,
            },
            {
                question: "What happens to the mass number during beta-minus decay?",
                options: ["Increases by 1", 
                        "Decreases by 1", 
                        "Stays the same", 
                        "Decreases by 2"],
                correctAnswer: 2,
            },
            {
                question: "The equation E = mc² shows that:",
                options: ["Energy is created from nothing", 
                        "Mass can be converted to energy", 
                        "Energy and mass are unrelated", 
                        "Energy is always conserved separately from mass"],
                correctAnswer: 1,
            },
            {
                question: "Which type of radiation has the shortest range in air?",
                options: ["Alpha", 
                        "Beta", 
                        "Gamma", 
                        "X-ray"],
                correctAnswer: 0,
            },
            {
                question: "Which scientist is credited with discovering the nucleus through the gold foil experiment?",
                options: ["Thomson", 
                        "Bohr", 
                        "Rutherford", 
                        "Einstein"],
                correctAnswer: 2,
            },
        ],
    },

    {
        category: "2.6 electricity",
        questions: [
            {
                question: "What is the unit of electric current?",
                options: ["Volt", 
                        "Ampere", 
                        "Ohm", 
                        "Watt"],
                correctAnswer: 1,
            },
            {
                question: "Which law states that V = IR?",
                options: ["Kirchhoff's Law", 
                        "Ohm's Law", 
                        "Coulomb's Law", 
                        "Faraday's Law"],
                correctAnswer: 1,
            },
            {
                question: "What is the unit of electrical resistance?",
                options: ["Ampere", 
                        "Ohm", 
                        "Volt", 
                        "Watt"],
                correctAnswer: 1,
            },
            {
                question: "What is the unit of electrical power?",
                options: ["Watt", 
                        "Volt", 
                        "Ampere", 
                        "Ohm"],
                correctAnswer: 0,
            },
            {
                question: "Which quantity measures the potential difference across a component?",
                options: ["Current", 
                        "Voltage", 
                        "Resistance", 
                        "Power"],
                correctAnswer: 1,
            },
            {
                question: "In a series circuit, how does the current behave?",
                options: ["It is the same through all components", 
                        "It divides across components", 
                        "It increases at each resistor", 
                        "It decreases at each resistor"],
                correctAnswer: 0,
            },
            {
                question: "In a parallel circuit, how does the voltage behave?",
                options: ["It is the same across each branch", 
                        "It divides across each branch", 
                        "It increases in each branch", 
                        "It drops to zero across the branches"],
                correctAnswer: 0,
            },
            {
                question: "What happens to the total resistance when resistors are added in series?",
                options: ["Total resistance decreases", 
                        "Total resistance increases", 
                        "Total resistance stays the same", 
                        "Cannot be determined"],
                correctAnswer: 1,
            },
            {
                question: "What happens to the total resistance when resistors are added in parallel?",
                options: ["Total resistance decreases", 
                        "Total resistance increases", 
                        "Total resistance stays the same", 
                        "Cannot be determined"],
                correctAnswer: 0,
            },
            {
                question: "What is the correct equation for electrical power in terms of current and voltage?",
                options: ["P = IV", 
                        "P = I²R", 
                        "P = V² / R", 
                        "All of the above"],
                correctAnswer: 3,
            },
            {
                question: "If a resistor has a current of 2 A and a voltage of 12 V across it, what is its resistance?",
                options: ["6 Ω", 
                        "24 Ω", 
                        "10 Ω", 
                        "2 Ω"],
                correctAnswer: 0,
            },
            {
                question: "What is the current through a 10 Ω resistor connected across 20 V?",
                options: ["0.5 A", 
                        "2 A", 
                        "10 A", 
                        "200 A"],
                correctAnswer: 1,
            },
            {
                question: "Which device measures current in a circuit?",
                options: ["Voltmeter", 
                        "Ammeter", 
                        "Ohmmeter", 
                        "Wattmeter"],
                correctAnswer: 1,
            },
            {
                question: "Which device measures potential difference in a circuit?",
                options: ["Ammeter", 
                        "Voltmeter", 
                        "Ohmmeter", 
                        "Galvanometer"],
                correctAnswer: 1,
            },
            {
                question: "Which of these increases the electrical power dissipated in a resistor?",
                options: ["Increasing resistance only", 
                        "Increasing current only", 
                        "Increasing both current and voltage", 
                        "Decreasing voltage"],
                correctAnswer: 2,
            },
            {
                question: "What is the energy used by a 100 W bulb in 2 hours?",
                options: ["200 J", 
                        "720 kJ", 
                        "720 kWh", 
                        "200 kJ"],
                correctAnswer: 1,
            },
            {
                question: "Which type of circuit is most commonly used in household wiring?",
                options: ["Series", 
                        "Parallel", 
                        "Mixed", 
                        "None"],
                correctAnswer: 1,
            },
            {
                question: "Which is true for current in a parallel branch?",
                options: ["Current is the same in each branch", 
                        "Current divides according to resistance", 
                        "Current adds up to zero", 
                        "Current is always 1 A per branch"],
                correctAnswer: 1,
            },
            {
                question: "If voltage across a 4 Ω resistor is 12 V, what is the current?",
                options: ["3 A", 
                        "0.33 A", 
                        "48 A", 
                        "16 A"],
                correctAnswer: 0,
            },
            {
                question: "Which statement is correct about a superconductor?",
                options: ["Resistance decreases with temperature", 
                        "Resistance is zero below critical temperature", 
                        "Voltage increases with current", 
                        "Current decreases spontaneously"],
                correctAnswer: 1,
            },
            {
                question: "What is the total current drawn from a 12 V battery in a parallel circuit with 3 branches of 6 Ω, 12 Ω, and 4 Ω resistors?",
                options: ["3 A", 
                        "6 A", 
                        "5 A", 
                        "4 A"],
                correctAnswer: 2,
            },
            {
                question: "Which of these equations can be used to calculate energy dissipated in a resistor?",
                options: ["E = Pt", 
                        "E = I²Rt", 
                        "E = VIt", 
                        "All of the above"],
                correctAnswer: 3,
            },
            {
                question: "A resistor has a current of 0.5 A and power dissipation of 2 W. What is the voltage across it?",
                options: ["4 V", 
                        "1 V", 
                        "2 V", 
                        "0.5 V"],
                correctAnswer: 0,
            },
            {
                question: "In which component does the current lead the voltage?",
                options: ["Resistor", 
                        "Capacitor", 
                        "Inductor", 
                        "Battery"],
                correctAnswer: 1,
            },
            {
                question: "A 10 Ω resistor is connected across 5 V. How much power is dissipated?",
                options: ["2.5 W", 
                        "5 W", 
                        "0.5 W", 
                        "10 W"],
                correctAnswer: 0,
            }
        ]
    }
]