// Questions sorted by category (25 each)
// Content is copied from ChatGPT (Aka questions and options)

const questions = [
    {
        category: "3.1 physics investigation",
        questions: [
            {
                question: "What is the main purpose of repeating measurements in a physics investigation?",
                options: ["Reduce bias", 
                    "Improving accuracy because more is better", 
                    "Reduce random errors", 
                    "Eliminate systematic errors"],
                correctAnswer: 2,
            },
            {
                question: "Which of the following is a systematic error?",
                options: ["Misreading a scale once", 
                    "Using a stopwatch with a consistent delay", 
                    "Random parallax error", 
                    "Small hand-timing inconsistencies"],
                correctAnswer: 1,
            },
            {
                question: "Which graph best shows proportionality between two variables?",
                options: ["Straight line through origin", 
                    "Curved line through origin", 
                    "Horizontal line", 
                    "Parabola"],
                correctAnswer: 0,
            },
            {
                question: "In an experiment measuring acceleration due to gravity, which is a dependent variable?",
                options: ["Length of pendulum", 
                    "Time for oscillations", 
                    "Mass of the bob", 
                    "Stopwatch used in the experiment"],
                correctAnswer: 1,
            },
            {
                question: "Why is it important to control variables in an investigation?",
                options: ["Reduce systematic errors", 
                    "Increase repeatability", 
                    "Ensure only one factor affects results", 
                    "Make calculations easier"],
                correctAnswer: 2,
            },
            {
                question: "Which device is most appropriate to measure small lengths accurately?",
                options: ["Metre ruler", 
                    "Measuring tape", 
                    "Vernier calipers", 
                    "Stopwatch"],
                correctAnswer: 2,
            },
            {
                question: "What does the slope of a velocity-time graph represent?",
                options: ["Speed", 
                    "Distance", 
                    "Force", 
                    "Acceleration"],
                correctAnswer: 3,
            },
            {
                question: "What is the primary role of uncertainties in measurements?",
                options: ["Make data unreliable", 
                    "Show accuracy", 
                    "Replace errors", 
                    "Indicate confidence in results"],
                correctAnswer: 3,
            },
            {
                question: "If data points scatter around a straight lint, what is the relationship?",
                options: ["No relationship", 
                    "Inverse", 
                    "Approximate linear", 
                    "Quadratic"],
                correctAnswer: 2,
            },
            {
                question: "Which of the following improves precision?",
                options: ["Calibrating instruments", 
                    "Taking more repeats", 
                    "Using finer scale instruments", 
                    "Averaging data"],
                correctAnswer: 2,
            },
            {
                question: "Which part of a report explains why the method was chosen?",
                options: ["Introduction", 
                    "Results", 
                    "Discussion", 
                    "Conclusion"],
                correctAnswer: 0,
            },
            {
                question: "Why are averages of repeated values used?",
                options: ["Reducing bias", 
                    "Eliminate chances of systematic error", 
                    "Helps speed calculations", 
                    "Reducing impact of random error"],
                correctAnswer: 3,
            },
            {
                question: "What does a small percentage uncertainty indicate?",
                options: ["Very inaccurate data", 
                    "High reliability of measurements", 
                    "Systematic error is present", 
                    "Random error dominates"],
                correctAnswer: 1,
            },
            {
                question: "Which method reduces parallax error?",
                options: ["Read from above", 
                    "Using mirror scales", 
                    "Estimate between divisions", 
                    "Repeat measurements"],
                correctAnswer: 1,
            },
            {
                question: "Why are calibration checks performed on equipment?",
                options: ["Remove bias", 
                    "Detect systematic errors", 
                    "Increase precision of experiment", 
                    "Eliminate random errors"],
                correctAnswer: 1,
            },
            {
                question: "What is the independent variable in a pendulum investigation?",
                options: ["Period", 
                    "Amplitude", 
                    "Time", 
                    "Length"],
                correctAnswer: 3,
            },
           {
                question: "Which factor ensures validity of an experiment?",
                options: ["Repeated measurements", 
                    "Controlled variabiles", 
                    "Graphical analysis", 
                    "Percentage error calculation"],
                correctAnswer: 1,
            },
            {
                question: "Why should anomalous data not be automatically discarded?",
                options: ["It's always incorrect", 
                    "It may reveal systematic errors", 
                    "It reduces accuracy", 
                    "It decreases precision"],
                correctAnswer: 1,
            },
            {
                question: "Which uncertainty calculation is correct for a single measurement with resolution ±0.1 cm?",
                options: ["±0.05 cm", 
                    "±0.1 cm", 
                    "±0.2 cm", 
                    "±1 cm"],
                correctAnswer: 1,
            },
            {
                question: "In analysing a linear relationship, which calculation best confirms proportionality?",
                options: ["Difference between results", 
                    "Ratio of variables", 
                    "Plot of inverse values", 
                    "Mean of results"],
                correctAnswer: 1,
            },
            {
                question: "What is the best reason to draw a line of best fit?",
                options: ["Connect all points", 
                    "Reduce anomalies", 
                    "Improve accuracy", 
                    "Show underlying trend"],
                correctAnswer: 2,
            },
            {
                question: "Which factor does NOT affect reliability of results?",
                options: ["Choice of theory", 
                    "Number of repeats", 
                    "Consistency of methods", 
                    "Random error size"],
                correctAnswer: 0,
            },
            {
                question: "When is it appropriate to use a log-log graph?",
                options: ["For proportional relationships", 
                    "For exponential/power laws", 
                    "For straight-line data", 
                    "For inverse linear data"],
                correctAnswer: 1,
            },
            {
                question: "What does “evaluation” in a report mainly involve?",
                options: ["Repeating results", 
                    "Identifying improvements and error sources", 
                    "Writing conclusion of experiment investigated", 
                    "Final analysis of data collected"],
                correctAnswer: 1,
            },
            {
                question: "Why should units always be included in results?",
                options: ["For neatness", 
                    "They indicate", 
                    "They prevent systematic errors", 
                    "They improve precision"],
                correctAnswer: 1,
            },
        ],
    },

    {
        category: "3.3 wave systems",
        questions: [
            {
                question: "What condition is required for standing waves to form?",
                options: ["Different frequencies", 
                    "Identical frequency and amplitude", 
                    "Opposite directions", 
                    "Both B and C"],
                correctAnswer: 3,
            },
            {
                question: "At an antinode of a standing wave, particle displacement is:",
                options: ["Zero", 
                    "Maximum", 
                    "Minimum velocity", 
                    "Constant"],
                correctAnswer: 1,
            },
            {
                question: "In a string fixed at both ends, the second harmonic has:",
                options: ["1 Loop", 
                    "2 loops", 
                    "3 loops", 
                    "4 loops"],
                correctAnswer: 1,
            },
            {
                question: "What is the path difference for destructive interference?",
                options: ["0λ", 
                    "nλ", 
                    "(n + ½)λ", 
                    "2nλ"],
                correctAnswer: 2,
            },
            {
                question: "In two-source interference, bright fringes occur where waves are:",
                options: ["Out of phase", 
                    "In phase", 
                    "Randomly phased", 
                    "Absorbed"],
                correctAnswer: 1,
            },
            {
                question: "The intensity of a wave is proportional to:",
                options: ["Velocity", 
                    "Frequency", 
                    "Wavelength", 
                    "Amplitude²"],
                correctAnswer: 3,
            },
            {
                question: "For double-slit interference, fringe separation increases when:",
                options: ["Wavelength decreases", 
                    "Slit spacing increases", 
                    "Screen distance increases", 
                    "Frequency increases"],
                correctAnswer: 2,
            },
            {
                question: "A diffraction grating gives sharper maxima than double slits because:",
                options: ["Many slits interfere", 
                    "More light passes", 
                    "Narrower slits used", 
                    "Wavelength is shorter"],
                correctAnswer: 0,
            },
            {
                question: "In a diffraction grating, the grating equation is:",
                options: ["nλ = d sinθ", 
                    "λ = d cosθ", 
                    "sinθ = λ/d", 
                    "nλ = d/θ"],
                correctAnswer: 0,
            },
            {
                question: "The first-order maximum occurs when:",
                options: ["Path difference = λ", 
                    "Path difference = ½λ", 
                    "Path difference = 2λ", 
                    "Path difference = 0"],
                correctAnswer: 0,
            },
            {
                question: "Which harmonic is missing in a closed pipe?",
                options: ["Odd", 
                    "All", 
                    "Even", 
                    "None"],
                correctAnswer: 2,
            },
            {
                question: "At resonance in a string system:",
                options: ["Energy transfer is minimal", 
                    "Standing wave forms", 
                    "Frequency is zero", 
                    "Wavelength infinite"],
                correctAnswer: 1,
            },
            {
                question: "A phase difference of π radians corresponds to:",
                options: ["Constructive interference", 
                    "Deconstructive interference", 
                    "Resonance", 
                    "Beats"],
                correctAnswer: 1,
            },
            {
                question: "Why are central maxima brightest in diffraction?",
                options: ["Shorter path difference", 
                    "All slits in phase", 
                    "Larger wavelength", 
                    "Narrower slit"],
                correctAnswer: 1,
            },
            {
                question: "The fringe separation in a two-source interference pattern is proportional to:",
                options: ["1/λ", 
                    "λ", 
                    "1/d", 
                    "1/L"],
                correctAnswer: 1,
            },
            {
                question: "For two sources to form a stable interference pattern, they must be:",
                options: ["Coherent", 
                    "Equal amplitude", 
                    "Perpendicular", 
                    "Seperated widely"],
                correctAnswer: 0,
            },
           {
                question: "Beats occur due to...",
                options: ["Reflection", 
                    "Refraction", 
                    "Interference of slightly different frequencies", 
                    "Harmonics"],
                correctAnswer: 2,
            },
            {
                question: "The beat frequency equals:",
                options: ["Sum of frequencies", 
                    "Product of frequencies", 
                    "Average frequency", 
                    "Difference of frequencies"],
                correctAnswer: 3,
            },
            {
                question: "What happens to harmonic frequency if string tension increases?",
                options: ["Increases", 
                    "Decreases", 
                    "Stays constant", 
                    "Zero"],
                correctAnswer: 0,
            },
            {
                question: "Why does sound diffract more than light?",
                options: ["Higher frequency", 
                    "Smaller wavelength relative to obstacles", 
                    "Lower frequency", 
                    "Longer wavelength relative to obstacles"],
                correctAnswer: 3,
            },
            {
                question: "A node in a standing wave has:",
                options: ["Maximum displacement", 
                    "Minimum displacement", 
                    "Zero displacement", 
                    "Constant motion"],
                correctAnswer: 2,
            },
            {
                question: "Which factor does NOT affect wave speed on a string?",
                options: ["Length", 
                    "Tension", 
                    "Density", 
                    "Mass per unit length"],
                correctAnswer: 0,
            },
            {
                question: "Diffraction is most significant when:",
                options: ["λ ≫ slit width", 
                    "λ ≈ slit width", 
                    "λ ≪ slit width", 
                    "λ = 0"],
                correctAnswer: 1,
            },
            {
                question: "In two-slit interference, if one slit is closed:",
                options: ["Pattern unchanged", 
                    "No interference fringes", 
                    "Double intensity", 
                    "Smaller wavelength"],
                correctAnswer: 1,
            },
            {
                question: "Which best explains resonance in air columns?",
                options: ["Beats", 
                    "Refraction", 
                    "Matching natural frequency with driving frequency", 
                    "Phase difference"],
                correctAnswer: 2,
            },
        ],
    },
        //  Starting from this point on, I have asked ChatGPT to put the content in the format of an array like mine
        //  This is to save time from now on
    {
        category: "3.4 mechanical systems",
        questions: [
            {
            
                question: "Which quantity is conserved in an isolated collision, regardless of elasticity?",
                options: ["Kinetic energy", 
                    "Momentum", 
                    "Angular velocity", 
                    "Force"],
                correctAnswer: 1,
            },
            {
                question: "Torque is defined as:",
                options: ["Force x time", 
                    "Force ÷ distance", 
                    "Force x distance", 
                    "Work ÷ time"],
                correctAnswer: 2,
            },
            {
                question: "Moment of inertia depends on:",
                options: ["Mass only", 
                    "Mass distribution", 
                    "Velocity", 
                    "Acceleration"],
                correctAnswer: 1,
            },
            {
                question: "The angular momentum of a system changes when:",
                options: ["Torque is zero", 
                    "External torque acts", 
                    "Velocity is constant", 
                    "Mass is conserved"],
                correctAnswer: 1,
            },
            {
                question: "Centripetal force acts:",
                options: ["Outward from the circle", 
                    "Tangential to the circle", 
                    "Inward towards the center", 
                    "Not at all"],
                correctAnswer: 2,
            },
            {
                question: "Work done on a rotating object equals:",
                options: ["Torque x angular displacement", 
                    "Torque x angular velocity", 
                    "Force x time", 
                    "Moment of inertia x radius"],
                correctAnswer: 0,
            },
            {
                question: "Kinetic energy of rotation is:",
                options: ["½ I ω²", 
                    "I ω", 
                    "½ m v²", 
                    "F x d"],
                correctAnswer: 0,
            },
            {
                question: "A projectile's horizontal acceleration (ignoring air resistance) is:",
                options: ["Constant", 
                    "Zero", 
                    "Increasing", 
                    "Decreasing"],
                correctAnswer: 1,
            },
            {
                question: "Angular velocity is measured in:",
                options: ["m/s", 
                    "radians/s", 
                    "m/s²", 
                    "Newtons"],
                correctAnswer: 1,
            },
            {
                question: "If net torque is zero, angular acceleration is:",
                options: ["Maximum", 
                    "Zero", 
                    "Infinite", 
                    "Constant"],
            correctAnswer: 1,
            },
            {
                question: "The restoring force in simple harmonic motion is proportional to:",
                options: ["Displacement", 
                    "Velocity", 
                    "Acceleration", 
                    "Time"],
                correctAnswer: 0,
            },
            {
                question: "For SHM, acceleration is:",
                options: ["In phase with displacement", 
                    "Opposite phase to displacement", 
                    "In phase with velocity", 
                    "Constant"],
                correctAnswer: 1,
            },
            {
                question: "The total energy in SHM is:",
                options: ["Constant", 
                    "Increasing", 
                    "Decreasing", 
                    "Zero"],
                correctAnswer: 0,
            },
            {
                question: "Period of a mass-spring system depends on:",
                options: ["Amplitude", 
                    "Mass and spring constant", 
                    "Velocity", 
                    "Force"],
                correctAnswer: 1,
            },
            {
                question: "In uniform circular motion, velocity is:",
                options: ["Constant magnitude, changing direction", 
                    "Constant vector", 
                    "Increasing", 
                    "Decreasing"],
                correctAnswer: 0,
            },
            {
                question: "Impulse equals:",
                options: ["Change in kinetic energy", 
                    "Change in momentum", 
                    "Force x distance", 
                    "Mass x acceleration"],
                correctAnswer: 1,
            },
            {
                question: "For a rolling object without slipping, v equals:",
                options: ["ω x r", 
                    "ω ÷ r", 
                    "r ÷ ω", 
                    "ω x r²"],
                correctAnswer: 0,
            },
            {
                question: "Which collision type conserves both kinetic energy and momentum?",
                options: ["Inelastic", 
                    "Elastic", 
                    "Explosion", 
                    "Plastic"],
                correctAnswer: 1,
            },
            {
                question: "The centripetal acceleration formula is:",
                options: ["v² / r", 
                    "v / r²", 
                    "r / v²", 
                    "a / F"],
                correctAnswer: 0,
            },
            {
                question: "Angular frequency ω relates to period T by:",
                options: ["ω = 1/T", 
                    "ω = 2π/T", 
                    "ω = T/2π", 
                    "ω = T"],
                correctAnswer: 1,
            },
            {
                question: "If force and displacement are perpendicular, work done is:",
                options: ["Maximum", 
                    "Minimum", 
                    "Zero", 
                    "Constant"],
                correctAnswer: 2,
            },
            {
                question: "Power is the rate of change of:",
                options: ["Force", 
                    "Acceleration", 
                    "Work", 
                    "Displacement"],
                correctAnswer: 2,
            },
            {
                question: "When a body is in equilibrium, net force and net torque are:",
                options: ["Zero and zero", 
                    "Zero and non-zero", 
                    "Non-zero and zero", 
                    "Both non-zero"],
                correctAnswer: 0,
            },
            {
                question: "Which has the greater moment of inertia?",
                options: ["Mass near axis", 
                    "Mass far from axis", 
                    "Mass evenly distributed", 
                    "Massless rod"],
                correctAnswer: 1,
            },
            {
                question: "For circular motion, frequency f relates to angular velocity ω as:",
                options: ["f = ω", 
                    "f = ω / 2π", 
                    "f = 2πω", 
                    "f = 1/ω"],
                correctAnswer: 1,
            },
        ],
    },

    {
        category: "3.5 modern physics",
        questions: [
            {
                question: "What is the threshold frequency in the photoelectric effect?",
                options: [
                    "Minimum frequency needed to emit electrons",
                    "Maximum frequency before emission stops",
                    "Frequency of emitted electrons",
                    "Average photon frequency"],
                correctAnswer: 0,
            },
            {
                question: "Increasing light intensity in the photoelectric effect increases:",
                options: [
                    "Electron speed",
                    "Electron number emitted",
                    "Threshold frequency",
                    "Work function"],
                correctAnswer: 1,
            },
            {
                question: "Einstein's photoelectric equation is:",
                options: [
                    "E = hf - Φ",
                    "E = mc²",
                    "E = hf/λ",
                    "E = ½mv²"],
                correctAnswer: 0,
            },
            {
                question: "The photon energy depends on:",
                options: [
                    "Intensity",
                    "Frequency",
                    "Amplitude",
                    "Speed of light squared"],
                correctAnswer: 1,
            },
            {
                question: "Which experiment confirmed wave-particle duality of electrons?",
                options: [
                    "Photoelectric effect",
                    "Compton scattering",
                    "Electron diffraction",
                    "Gold foil experiment"],
                correctAnswer: 2,
            },
            {
                question: "In de Broglie's theory, wavelength is inversely proportional to:",
                options: [
                    "Momentum",
                    "Frequency",
                    "Energy",
                    "Mass"],
                correctAnswer: 0,
            },
            {
                question: "Which particle has the smallest de Broglie wavelength at equal momentum?",
                options: [
                    "Electron",
                    "Proton",
                    "Neutron",
                    "Photon"],
                correctAnswer: 3,
            },
            {
                question: "In special relativity, time dilation occurs because:",
                options: [
                    "Speed of light changes",
                    "Moving clocks tick slower",
                    "Mass decreases",
                    "Energy decreases"],
                correctAnswer: 1,
            },
            {
                question: "Which quantity is invariant in relativity?",
                options: [
                    "Time interval",
                    "Mass",
                    "Speed of light",
                    "Momentum"],
                correctAnswer: 2,
            },
            {
                question: "E = mc² shows:",
                options: [
                    "Energy is proportional to velocity squared",
                    "Mass and energy equivalence",
                    "Energy conserved, mass not",
                    "Energy inversely proportional to mass"],
                correctAnswer: 1,
            },
            {
                question: "Which spectral lines result from electron transitions?",
                options: [
                    "Atomic emission spectra",
                    "Continuous spectrum",
                    "Blackbody radiation",
                    "X-ray absorption"],
                correctAnswer: 0,
            },
            {
                question: "Energy levels in atoms are:",
                options: [
                    "Continuous",
                    "Random",
                    "Quantised",
                    "Infinite"],
                correctAnswer: 2,
            },
            {
                question: "The uncertainty principle links:",
                options: [
                    "Position and velocity",
                    "Position and momentum",
                    "Energy and mass",
                    "Time and frequency"],
                correctAnswer: 1,
            },
            {
                question: "What happens in pair production?",
                options: [
                    "Electron splits",
                    "Photon creates particle and antiparticle",
                    "Proton emits neutron",
                    "Neutron decays"],
                correctAnswer: 1,
            },
            {
                question: "Which radiation is stopped by paper?",
                options: [
                    "Alpha",
                    "Beta",
                    "Gamma",
                    "X-ray"],
                correctAnswer: 0,
            },
            {
                question: "Half-life is defined as:",
                options: [
                    "Time for all nuclei to decay",
                    "Time for half the nuclei to decay",
                    "Time for half radiation blocked",
                    "Time for activity to double"],
                correctAnswer: 1,
            },
            {
                question: "Which force holds the nucleus together?",
                options: [
                    "Electrostatic",
                    "Gravitational",
                    "Strong nuclear",
                    "Weak nuclear"],
                correctAnswer: 2,
            },
            {
                question: "In nuclear fission:",
                options: [
                    "Small nuclei join to form larger",
                    "Large nucleus splits into smaller",
                    "Electrons absorb energy",
                    "Neutrons decay"],
                correctAnswer: 1,
            },
            {
                question: "Binding energy per nucleon is highest for:",
                options: [
                    "Hydrogen",
                    "Iron",
                    "Uranium",
                    "Helium"],
                correctAnswer: 1,
            },
            {
                question: "Which effect demonstrates photons have momentum?",
                options: [
                    "Photoelectric effect",
                    "Compton scattering",
                    "Refraction",
                    "Diffraction grating"],
                correctAnswer: 1,
            },
            {
                question: "Gamma radiation differs from X-rays because:",
                options: [
                    "Higher velocity",
                    "Nuclear origin",
                    "Lower frequency",
                    "More massive photons"],
                correctAnswer: 1,
            },
            {
                question: "Which variable does NOT affect radioactive decay?",
                options: [
                    "Pressure",
                    "Temperature",
                    "Magnetic field",
                    "None of these"],
                correctAnswer: 3,
            },
            {
                question: "Rest mass of a photon is:",
                options: [
                    "Zero",
                    "Very small",
                    "Equal to electron mass",
                    "Infinite"],
                correctAnswer: 0,
            },
            {
                question: "The Compton effect showed that photons have:",
                options: [
                    "Mass",
                    "Charge",
                    "Momentum",
                    "Volume"],
                correctAnswer: 2,
            },
            {
                question: "Relativistic mass increase is significant when:",
                options: [
                    "Velocity ≪ c",
                    "Velocity ≈ c",
                    "Acceleration is small",
                    "Time is large"],
                correctAnswer: 1,
            },
        ],
    },

    {
        category: "3.6 electrical systems",
        questions: [
            {
                question: "The RMS value of an AC supply is defined as:",
                options: [
                    "The average current over a cycle",
                    "The peak current",
                    "The DC current giving same power",
                    "The maximum instantaneous voltage"],
                correctAnswer: 2,
            },
            {
                question: "In a purely resistive AC circuit, current and voltage are:",
                options: [
                    "In phase",
                    "90° out of phase",
                    "180° out of phase",
                    "Constant with time"],
                correctAnswer: 0,
            },
            {
                question: "Reactance of a capacitor is given by:",
                options: [
                    "XL = 2πfL",
                    "XC = 1 / (2πfC)",
                    "XC = 2πfC",
                    "XL = 1 / (2πfL)"],
                correctAnswer: 1,
            },
            {
                question: "For an inductor in AC, current lags voltage by:",
                options: [
                    "0°",
                    "45°",
                    "90°",
                    "180°"],
                correctAnswer: 2,
            },
            {
                question: "At resonance in an RLC circuit:",
                options: [
                    "XL = XC",
                    "XL > XC",
                    "XL < XC",
                    "XL = 0"],
                correctAnswer: 0,
            },
            {
                question: "Impedance of a series RLC circuit is:",
                options: [
                    "R + XL + XC",
                    "√(R² + (XL – XC)²)",
                    "R² + XL² + XC²",
                    "XL – XC"],
                correctAnswer: 1,
            },
            {
                question: "Power factor is defined as:",
                options: [
                    "P / V",
                    "cosϕ",
                    "sinϕ",
                    "tanϕ"],
                correctAnswer: 1,
            },
            {
                question: "Real power in AC is calculated as:",
                options: [
                    "VI",
                    "VI cosϕ",
                    "VI sinϕ",
                    "V² / R"],
                correctAnswer: 1,
            },
            {
                question: "In a transformer, the ratio of voltages equals:",
                options: [
                    "Ratio of turns",
                    "Square of turns ratio",
                    "Inverse of turns ratio",
                    "Resistance ratio"],
                correctAnswer: 0,
            },
            {
                question: "If a transformer is step-down, then:",
                options: [
                    "Ns > Np",
                    "Ns < Np",
                    "Vs > Vp",
                    "Is < Ip"],
                correctAnswer: 1,
            },
            {
                question: "A pure capacitor in AC has:",
                options: [
                    "Power factor = 0",
                    "Power factor = 1",
                    "Resistive power loss",
                    "Phase angle = 0°"],
                correctAnswer: 0,
            },
            {
                question: "Inductive reactance increases with:",
                options: [
                    "Decreasing frequency",
                    "Increasing frequency",
                    "Decreasing inductance",
                    "Decreasing resistance"],
                correctAnswer: 1,
            },
            {
                question: "Which component stores energy in a magnetic field?",
                options: [
                    "Resistor",
                    "Capacitor",
                    "Inductor",
                    "Transformer"],
                correctAnswer: 2,
            },
            {
                question: "Which component stores energy in an electric field?",
                options: [
                    "Resistor",
                    "Capacitor",
                    "Inductor",
                    "Diode"],
                correctAnswer: 1,
            },
            {
                question: "At resonance, impedance of an RLC circuit is:",
                options: [
                    "Minimum",
                    "Maximum",
                    "Zero",
                    "Infinite"],
                correctAnswer: 0,
            },
            {
                question: "The unit of inductance is:",
                options: [
                    "Farad",
                    "Henry",
                    "Ohm",
                    "Tesla"],
                correctAnswer: 1,
            },
            {
                question: "The unit of capacitance is:",
                options: [
                    "Coulomb",
                    "Farad",
                    "Henry",
                    "Volt"],
                correctAnswer: 1,
            },
            {
                question: "If frequency doubles, capacitive reactance:",
                options: [
                    "Halves",
                    "Doubles",
                    "Stays same",
                    "Quadruples"],
                correctAnswer: 0,
            },
            {
                question: "If frequency doubles, inductive reactance:",
                options: [
                    "Halves",
                    "Doubles",
                    "Stays same",
                    "Quadruples"],
                correctAnswer: 1,
            },
            {
                question: "Which phasor diagram represents a purely inductive circuit?",
                options: [
                    "Current leads voltage 90°",
                    "Voltage leads current 90°",
                    "Current in phase with voltage",
                    "Current opposite to voltage"],
                correctAnswer: 1,
            },
            {
                question: "Which loss is reduced using laminated transformer cores?",
                options: [
                    "Copper losses",
                    "Hysteresis losses",
                    "Eddy current losses",
                    "Radiation losses"],
                correctAnswer: 2,
            },
            {
                question: "In an ideal transformer:",
                options: [
                    "Power in < Power out",
                    "Power in = Power out",
                    "Power in > Power out",
                    "Power loss is maximum"],
                correctAnswer: 1,
            },
            {
                question: "Phase angle ϕ is defined between:",
                options: [
                    "Resistance and reactance",
                    "Current and voltage",
                    "XL and XC",
                    "Power and energy"],
                correctAnswer: 1,
            },
            {
                question: "A choke coil is used to:",
                options: [
                    "Increase voltage",
                    "Reduce AC current without loss",
                    "Store energy in electric field",
                    "Rectify AC"],
                correctAnswer: 1,
            },
            {
                question: "In resonance, current is:",
                options: [
                    "Minimum",
                    "Maximum",
                    "Zero",
                    "Infinite"],
                correctAnswer: 1,
            },
        ],
    },

    {
        category: "3.7 physics response",
        questions: [
            {
                question: "Which law explains why greenhouse gases trap heat in Earth's atmosphere?",
                options: [
                    "Conservation of momentum",
                    "Stefan-Boltzmann law",
                    "Coulomb's law",
                    "Hooke's law"],
                correctAnswer: 1,
            },
            {
                question: "Which radiation type is used in cancer treatment?",
                options: [
                    "Alpha",
                    "Beta",
                    "Gamma",
                    "Infrared"],
                correctAnswer: 2,
            },
            {
                question: "Nuclear fission is used in reactors because it:",
                options: [
                    "Releases large energy per reaction",
                    "Produces no waste",
                    "Requires low temperatures",
                    "Is safer than fusion"],
                correctAnswer: 0,
            },
            {
                question: "A major challenge of nuclear fusion power is:",
                options: [
                    "Low fuel availability",
                    "High containment temperatures",
                    "Weak energy release",
                    "Excessive radioactive waste"],
                correctAnswer: 1,
            },
            {
                question: "Which renewable energy source relies on electromagnetic induction?",
                options: [
                    "Solar panels",
                    "Wind turbines",
                    "Geothermal heat",
                    "Biomass combustion"],
                correctAnswer: 1,
            },
            {
                question: "The efficiency of solar cells depends strongly on:",
                options: [
                    "Photon energy relative to band gap",
                    "Mass of the panel",
                    "Resistance of wires",
                    "Voltage of batteries"],
                correctAnswer: 0,
            },
            {
                question: "Which form of radiation is most ionising?",
                options: [
                    "Alpha",
                    "Beta",
                    "Gamma",
                    "Microwaves"],
                correctAnswer: 0,
            },
            {
                question: "Which energy source has the highest energy density?",
                options: [
                    "Coal",
                    "Hydrogen fuel",
                    "Uranium fission",
                    "Natural gas"],
                correctAnswer: 2,
            },
            {
                question: "Superconductors are useful in power grids because they:",
                options: [
                    "Increase resistance",
                    "Reduce transmission losses",
                    "Convert AC to DC",
                    "Produce energy"],
                correctAnswer: 1,
            },
            {
                question: "Why are LED lights more efficient than incandescent bulbs?",
                options: [
                    "Higher resistance",
                    "Emit light via electron transitions",
                    "Emit more infrared",
                    "Use higher currents"],
                correctAnswer: 1,
            },
            {
                question: "Which law explains how rotation of the turbine generates electricity?",
                options: [
                    "Bernoulli's principle",
                    "Faraday's law",
                    "Newton's second law",
                    "Snell's law"],
                correctAnswer: 1,
            },
            {
                question: "Which isotope is commonly used in nuclear power reactors?",
                options: [
                    "U-235",
                    "C-14",
                    "I-131",
                    "U-238"],
                correctAnswer: 0,
            },
            {
                question: "Which physics concept is critical for MRI machines?",
                options: [
                    "Nuclear magnetic resonance",
                    "Wave-particle duality",
                    "Quantum tunnelling",
                    "Photoelectric effect"],
                correctAnswer: 0,
            },
            {
                question: "In hydroelectric dams, potential energy of water is converted into:",
                options: [
                    "Kinetic energy only",
                    "Electrical energy",
                    "Nuclear energy",
                    "Heat energy"],
                correctAnswer: 1,
            },
            {
                question: "Why are HV transmission lines used?",
                options: [
                    "Reduce resistance",
                    "Reduce current to lower power loss",
                    "Increase current for efficiency",
                    "Eliminate reactance"],
                correctAnswer: 1,
            },
            {
                question: "What environmental issue is most linked to fossil fuel use?",
                options: [
                    "Stratospheric ozone depletion",
                    "Global warming from CO₂",
                    "Water acidification",
                    "Nuclear waste"],
                correctAnswer: 1,
            },
            {
                question: "What physics principle allows microwaves to heat food?",
                options: [
                    "Photon emission",
                    "Molecular vibration resonance",
                    "Gamma absorption",
                    "Photoelectric effect"],
                correctAnswer: 1,
            },
            {
                question: "The half-life concept is important in:",
                options: [
                    "Measuring radioactive decay",
                    "Calculating electric potential",
                    "Determining capacitor charge",
                    "Calculating frequency"],
                correctAnswer: 0,
            },
            {
                question: "Which device converts AC voltage levels efficiently?",
                options: [
                    "Resistor",
                    "Diode",
                    "Transformer",
                    "Capacitor"],
                correctAnswer: 2,
            },
            {
                question: "Nuclear fusion uses which fuel most commonly?",
                options: [
                    "Uranium",
                    "Deuterium and tritium",
                    "Carbon",
                    "Plutonium"],
                correctAnswer: 1,
            },
            {
                question: "Which principle makes GPS require relativity corrections?",
                options: [
                    "Special relativity only",
                    "General relativity only",
                    "Both special and general relativity",
                    "Quantum mechanics"],
                correctAnswer: 2,
            },
            {
                question: "Which wave property is essential for fibre optic communication?",
                options: [
                    "Total internal reflection",
                    "Diffraction",
                    "Superposition",
                    "Polarisation"],
                correctAnswer: 0,
            },
            {
                question: "Which type of nuclear reaction powers the Sun?",
                options: [
                    "Fission of hydrogen",
                    "Fusion of hydrogen",
                    "Fission of helium",
                    "Fusion of uranium"],
                correctAnswer: 1,
            },
            {
                question: "What is a key socio-scientific concern with nuclear power?",
                options: [
                    "High CO₂ emissions",
                    "Radioactive waste disposal",
                    "Weak energy density",
                    "Excessive water use"],
                correctAnswer: 1,
            },
            {
                question: "Which physical principle explains why wind turbines slow the wind?",
                options: [
                    "Newton's third law",
                    "Archimedes' principle",
                    "Conservation of charge",
                    "Hooke's law"],
                correctAnswer: 0,
            },
        ]
    }
]