// Questions sorted by category (25 each)
const questions = [
    {
        category: "3.4 thermo-chemistry",
        questions: [
            {
                question: "In thermochemistry, what is the definition of Entropy?",
                options: ["The energy change of a chemical system", 
                    "The disorder/randomness of a chemical system", 
                    "The amount of energy absorbed/released in a chemical system", 
                    "The concentration of the products produced in a chemical system"],
                correctAnswer: 1,
            },
            {
                question: "When going down any group of elements from the periodic table of elements, what is the trend for atomic radius?",
                options: ["Atomic radius decreases", 
                    "Atomic radius doesn't change at all", 
                    "Atomic radius increases", 
                    "Atomic radius doesn't change, but it is stronger"],
                correctAnswer: 2,
            },
            {
                question: "A molecule with 5 bonding pairs, and 1 non-bonding pair, is called a?",
                options: ["Square based pyramid", 
                    "Trigonal pyramid", 
                    "Square planar", 
                    "Octahedral"],
                correctAnswer: 0,
            },
            {
                question: "What is the maximum number of electrons for a 'd' orbital?",
                options: ["5", 
                    "15", 
                    "6", 
                    "10"],
                correctAnswer: 3,
            },
            {
                question: "Hydrogen bonding is a strong type of intermolecular bonding. What is the requirement for it to occur?",
                options: ["If hydrogen is present connected to any atom", 
                    "If hydrogen is present connected to a non-metal", 
                    "If hydrogen is present connected to a highly electronegative atom", 
                    "If hydrogen is present connected to a carbon"],
                correctAnswer: 2,
            },
            {
                question: "In thermochemistry, what is the definition of enthalpy change? (ΔH)",
                options: ["Total energy of a chemical system", 
                    "Energy required to break a bond in a molecule", 
                    "The heat absorbed OR released of a chemical system at constant pressure", 
                    "The heat absorbed OR released of a chemical system at constant volume"],
                correctAnswer: 2,
            },
            {
                question: "Which of the following choices BEST describes an exothermic reaction?",
                options: ["Heat is absorbed from its surroundings", 
                    "No heat exchange occurs", 
                    "Heat is released into the surroundings", 
                    "The temperature of the chemical system is decreased with no energy transfer"],
                correctAnswer: 2,
            },
            {
                question: "What is the main factor that affects the strength of intermolecular forces?",
                options: ["The size and shape of the molecule", 
                    "The number of neutrons present in the nucleus", 
                    "The ionic charge of atoms", 
                    "The appearance or colour of the substance"],
                correctAnswer: 0,
            },
            {
                question: "Which statement best describes the relationship between temperature and particle kinetic energy?",
                options: ["The temperature of the substance decreases as the kinetic energy increases", 
                    "Temperature is directly proportional to the average kinetic energy of particles", 
                    "Temperature is unrelated to kinetic energy, therefore there is no change in temperature", 
                    "Temperature is the total kinetic energy of all particles"],
                correctAnswer: 1,
            },
            {
                question: "In thermochemistry, what is the definition of standard enthalpy of formation (ΔHf°)?",
                options: ["The enthalpy change during the combustion of a compound", 
                    "The heat absorbed when a substance melts from solid to a liquid state", 
                    "The energy required to break one mole of bonds in a chemical system", 
                    "The enthalpy change when one mole of a compound is formed from its elements in their standard states"],
                correctAnswer: 3,
            },
            {
                question: "What type of bond is formed when electrons are shared between atoms?",
                options: ["Ionic bond", 
                    "Covalent bond", 
                    "Metallic bond", 
                    "Hydrogen bond"],
                correctAnswer: 1,
            },
            {
                question: "What happens to the entropy of a chemical system when a solid melts?",
                options: ["It increases", 
                    "It decreases", 
                    "Nothing changes", 
                    "Entropy doesn't change, Enthalpy does"],
                correctAnswer: 0,
            },
            {
                question: "At high temperatures, spontaneity is favoured if:",
                options: ["ΔH > 0 and ΔS < 0", 
                    "ΔH < 0 and ΔS < 0", 
                    "ΔH > 0 and ΔS > 0", 
                    "ΔH < 0 and ΔS > 0"],
                correctAnswer: 2,
            },
            {
                question: "In thermochemistry, the symbol ΔG represents:",
                options: ["Enthalpy change", 
                    "Entropy change of a system", 
                    "Activation energy change", 
                    "Gibbs free energy change"],
                correctAnswer: 3,
            },
            {
                question: "Which process is an example of entropy increasing in a chemical system (ΔS > 0)?",
                options: ["Condensation of water vapour", 
                    "Freezing water", 
                    "Dissolving NaCl in water", 
                    "Compressing a gas"],
                correctAnswer: 2,
            },
            {
                question: "Graphite, believe it or not, has the ability to conduct electricity. Why?",
                options: ["It has delocalised electrons between layers", 
                    "Each carbon atom makes four bonds", 
                    "It contains ions that can move freely", 
                    "It is a molecular solid with weak bonds"],
                correctAnswer: 0,
            },
            {
                question: "Silicon dioxide (SiO₂) has a very high melting point (1713°C). Why?",
                options: ["It has weak intermolecular forces", 
                    "It has strong covalent bonds in a 3D network", 
                    "It contains delocalised electrons", 
                    "It has high entropy, thus harder to break down"],
                correctAnswer: 1,
            },
            {
                question: "Which molecule has hydrogen bonding between its molecules?",
                options: ["CH₄", 
                    "CO₂", 
                    "Cl₂", 
                    "NH₃"],
                correctAnswer: 3,
            },
            {
                question: "Which statement about metallic bonding is correct?",
                options: ["Metals are malleable because delocalised electrons allow layers of cations to slide", 
                    "Metals conduct electricity because electrons are localised", 
                    "Metals are brittle because of strong directional bonds", 
                    "Metallic bonding is weaker than dispersion forces"],
                correctAnswer: 0,
            },
            {
                question: "The bond angle in CH₄ is approximately:",
                options: ["90°", 
                    "120°", 
                    "109.5°", 
                    "180°"],
                correctAnswer: 1,
            },
            {
                question: "What is the molecular shape of Water, H₂O?",
                options: ["Linear", 
                    "Bent", 
                    "Trigonal planar", 
                    "Square planar"],
                correctAnswer: 1,
            },
            {
                question: "What is the molecular shape of Boron Triflouride, BF₃?",
                options: ["Tetrahedral", 
                    "Trigonal pyramid", 
                    "Trigonal planar", 
                    "Square based pyramid"],
                correctAnswer: 2,
            },
            {
                question: "Which molecule is non-polar overall despite having polar bonds?",
                options: ["NH₃", 
                    "H₂O", 
                    "CH₃Cl", 
                    "CO₂"],
                correctAnswer: 3,
            },
            {
                question: "The enthalpy change combustion of Ethene [ C₂H₄(g) + 3O₂(g) → 2CO₂(g) + 2H₂O(l) ] is -1411 kJ mol⁻¹. What does the negative sign indicate?",
                options: ["The products have more energy than the reactants", 
                    "Energy is absorbed from the surroundings, therefore endothermic", 
                    "Energy is released to the surroundings, therefore exothermic", 
                    "The reaction requires heat to proceed"],
                correctAnswer: 2,
            },
            {
                question: "Using Hess's Law, if the enthalpy change for reaction A is +150 kJ and reaction B is -200 kJ, what is the enthalpy change for the overall reaction A + B?",
                options: ["-350 kJ", 
                    "+350 kJ", 
                    "-50 kJ", 
                    "+50 kJ"],
                correctAnswer: 2,
            },
        ],
    },

    {
        category: "3.5 organic chemistry",
        questions: [
            {
                question: "Which reagent is commonly used to test for the presence of an alkene?",
                options: ["Tollen's reagent",
                    "Bromine water",
                    "Benedict's solution",
                    "Acidified potassium permanganate",],
                correctAnswer: 1,
            },
            {
                question: "Which functional group is present in an alcohol?",
                options: ["-COOH",
                    "-NH₂",
                    "-OH",
                    "-CHO",],
                correctAnswer: 2,
            },
            {
                question: "What type of reaction occurs when an alkene reacts with hydrogen gas in the presence of a catalyst?",
                options: ["Substitution",
                    "Polymerisation",
                    "Elimination",
                    "Addition",],
                correctAnswer: 3,
            },
            {
                question: "Which of the following is an isomer of butane?",
                options: ["Pentane",
                    "Propane",
                    "2-methylpropane",
                    "Ethane",],
                correctAnswer: 2,
            },
            {
                question: "The name but-2-ene means?",
                options: ["A double bond is on carbon 1.",
                    "It has 2 carbons in the chain.",
                    "It is an alkyne.",
                    "A double bond is on carbon 2.",],
                correctAnswer: 3,
            },
            {
                question: "What is produced when ethene reacts with Br₂?",
                options: ["Dibromoethane",
                    "Bromoethane",
                    "Polybromobiphenyl",
                    "Ethanol",],
                correctAnswer: 0,
            },
            {
                question: "The reaction of alkenes with H₂ in the presence of a Pt catalyst is called:",
                options: ["Halogenation",
                    "Hydrogenation",
                    "Oxidation",
                    "Polymerisation",],
                correctAnswer: 1,
            },
            {
                question: "Which of the following reagents, can be used to distinguish between alkanes and alkenes?",
                options: ["NaOH",
                    "AgNO₃",
                    "Bromine water",
                    "Acidified dichromate",],
                correctAnswer: 2,
            },
            {
                question: "Oxidation of a primary alcohol produces:",
                options: ["A ketone",
                    "An ester",
                    "An aldehyde",
                    "An alkene",],
                correctAnswer: 2,
            },
            {
                question: "Poly(ethene) is formed by:",
                options: ["Condensation polymerisation",
                    "Addition polymerisation",
                    "Hydrolysis",
                    "Oxidation",],
                correctAnswer: 1,
            },
            {
                question: "Nylon is an example of:",
                options: ["Condensation polymer",
                    "Radical polymer",
                    "Addition polymer",
                    "Isomeric polymer",],
                correctAnswer: 0,
            },
            {
                question: "Define the term isomers",
                options: ["Compounds with identical chemical properties",
                    "Compounds with the same molecular formula but different structures",
                    "Compounds that differ only in physical state",
                    "Compounds containing a carbonyl group",],
                correctAnswer: 1,
            },
            {
                question: "Define the term addition reaction:",
                options: ["A hydrogen atom is replaced by another atom or group",
                    "A molecule breaks down into two smaller ones",
                    "A monomer forms a polymer",
                    "Two molecules combine to form one larger molecule",],
                correctAnswer: 3,
            },
            {
                question: "Which product forms when ethene reacts with HCl?",
                options: ["Poly(ethane)",
                    "Ethene",
                    "Ethane",
                    "Chloroethane",],
                correctAnswer: 3,
            },
            {
                question: "Which statement correctly defines saturated hydrocarbons?",
                options: ["Hydrocarbons that contain double or triple bonds",
                    "Hydrocarbons that contain only C-C single bonds",
                    "Hydrocarbons with rings",
                    "Hydrocarbons with halogenic substituents",],
                correctAnswer: 1,
            },
            {
                question: "Geometric (cis/trans) isomerism occurs because of:",
                options: ["Free rotation around single bonds",
                    "Restricted rotation around a C=C double bond",
                    "Resonance structures",
                    "Asymmetric carbons",],
                correctAnswer: 1,
            },
            {
                question: "What is the product of propanoyl chloride + NH₃?",
                options: ["Propanamine",
                    "Propanic acid",
                    "Propanamide",
                    "Propanoate",],
                correctAnswer: 2,
            },
            {
                question: "When carboxylic acids react with bases, what do they produce?",
                options: ["Alkanes",
                    "Salts",
                    "Esters",
                    "Alcohols",],
                correctAnswer: 1,
            },
            {
                question: "Which reagent oxidises ethanal to ethanoic acid?",
                options: ["Br₂",
                    "H₂/Ni",
                    "NaOH",
                    "Acidified Cr₂O₇²⁻",],
                correctAnswer: 3,
            },
            {
                question: "The reaction of alcohol + carboxylic acid (H₂SO₄ catalyst) forms:",
                options: ["Ester",
                    "Aldehyde",
                    "Ketone",
                    "Alkene",],
                correctAnswer: 0,
            },
            {
                question: "Amines are basic because:",
                options: ["They donate protons",
                    "The nitrogen lone pair accepts a proton",
                    "They contain a carbonyl group",
                    "They contain a -OH group",],
                correctAnswer: 1,
            },
            {
                question: "Which is an example of structural isomerism?",
                options: ["Butan-1-ol vs Butan-2-ol",
                    "cis-But-2-ene vs trans-But-2-ene",
                    "Mirror images of 2-butanol",
                    "CH₄ vs C₂H₆",],
                correctAnswer: 0,
            },
            {
                question: "What is the functional group in esters?",
                options: ["-OH",
                    "-COOH",
                    "-NH₂",
                    "-COOR (Where 'R' is a carbon chain)",],
                correctAnswer: 3,
            },
            {
                question: "The compound CH₃CH₂CH₂NH₂ is best named as:",
                options: ["Propanal",
                    "Propanol",
                    "Propanamide",
                    "Propanamine",],
                correctAnswer: 3,
            },
            {
                question: "Which functional group is present in propanone?",
                options: ["Alcohol",
                    "Ester",
                    "Amine",
                    "Ketone",],
                correctAnswer: 3,
            },
        ],
    },

    {
        category: "3.6 aqueous & equilibria chemistry",
        questions: [
            {
                question: "Which statement best defines dynamic equilibrium?",
                options: ["The forward reaction stops, and only the reverse occurs",
                    "The forward and reverse reactions occur at equal rates",
                    "The concentrations of reactants and products are equal",
                    "The reaction has gone to completion",],
                correctAnswer: 1,
            },
            {
                question: "The value of the equilibrium constant (Kc)...",
                options: ["Changes if temperature changes",
                    "Changes if pressure changes",
                    "Changes if concentration changes",
                    "Never changes",],
                correctAnswer: 0,
            },
            {
                question: "For the reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the equilibrium constant expression is:",
                options: ["[N₂][H₂]³ / [NH₃]²",
                    "[NH₃]² / [N₂][H₂]³",
                    "[NH₃] / [N₂][H₂]",
                    "[N₂][H₂] / [NH₃]",],
                correctAnswer: 1,
            },
            {
                question: "If Q > K for a reaction mixture, then that indicates...",
                options: ["The system is at equilibrium",
                    "The reaction will shift forward",
                    "The reaction will shift backward",
                    "The reaction has gone to completion",],
                correctAnswer: 2,
            },
            {
                question: "Which change does not affect the position of equilibrium?",
                options: ["Adding a reactant",
                    "Changing temperature",
                    "Adding a catalyst",
                    "Removing a product",],
                correctAnswer: 2,
            },
            {
                question: "In the equilibrium N₂O₄(g) ⇌ 2NO₂(g), a decrease in pressure favours...",
                options: ["N₂O₄",
                    "NO₂",
                    "No change",
                    "Both equally",],
                correctAnswer: 1,
            },
            {
                question: "Increasing temperature in an exothermic equilibrium will...",
                options: ["Shift equilibrium towards products",
                    "Shift equilibrium towards reactants",
                    "Increase K",
                    "Leave equilibrium unchanged",],
                correctAnswer: 1,
            },
            {
                question: "The Haber process (N₂ + 3H₂ ⇌ 2NH₃) is exothermic. Higher pressure favours...",
                options: ["Forward reaction",
                    "Reverse reaction",
                    "No change",
                    "Equal forward and reverse",],
                correctAnswer: 0,
            },
            {
                question: "When HCl(aq) is added to a saturated solution of sodium acetate, equilibrium shifts...",
                options: ["To dissolve more acetate",
                    "To precipitate acetic acid",
                    "To produce more NaOH",
                    "No shift",],
                correctAnswer: 1,
            },
            {
                question: "Which change increases the yield of SO₃ in 2SO₂(g) + O₂(g) ⇌ 2SO₃(g), ΔH = -196 kJ mol⁻¹?",
                options: ["Increase T, increase P",
                    "Increase T, decrease P",
                    "Decrease T, increase P",
                    "Decrease T, decrease P",],
                correctAnswer: 2,
            },
            {
                question: "Which is the correct definition of a Bronsted-Lowry acid?",
                options: ["Proton acceptor",
                    "Proton donor",
                    "Electron donator",
                    "Electron pair acceptor",],
                correctAnswer: 1,
            },
            {
                question: "Which species is amphiprotic?",
                options: ["H₂O",
                    "NaCl",
                    "CH₄",
                    "NH₃",],
                correctAnswer: 0,
            },
            {
                question: "A buffer solution resists pH change because?",
                options: ["It contains strong acids and bases",
                    "It contains a weak acid and its conjugate base",
                    "It contains only water",
                    "It reacts completely with added acid",],
                correctAnswer: 1,
            },
            {
                question: "Adding NaOH to a buffer made from CH₃COOH/CH₃COONa...",
                options: ["Decreases pH sharply",
                    "Inceases pH sharply",
                    "Causes a small increase in pH",
                    "Leaves pH unchanged",],
                correctAnswer: 2,
            },
            {
                question: "Which of the following salts produces a basic solution in water?",
                options: ["NaCl",
                    "NH₄Cl",
                    "CH₃COONa",
                    "KNO₃",],
                correctAnswer: 2,
            },
            {
                question: "Define the pH term",
                options: ["-log [OH⁻]",
                    "-log [H₃O⁺]",
                    "log [OH⁻]",
                    "log [H₃O⁺]",],
                correctAnswer: 1,
            },
            {
                question: "At 25 °C, the value of Kw is...",
                options: ["1 x 10⁻¹²",
                    "1 x 10⁻¹⁴",
                    "1 x 10⁻⁷",
                    "1 x 10⁻¹⁰",],
                correctAnswer: 1,
            },
            {
                question: "If the Ka of acetic acid is 1.8 x 10⁻⁵, its conjugate base (acetate) has a Kb of approximately...",
                options: ["1.8 x 10⁵",
                    "1 x 10⁻¹⁴",
                    "5.6 x 10⁻¹⁰",
                    "1.8 x 10⁻⁹",],
                correctAnswer: 2,
            },
            {
                question: "Which acid is strongest?",
                options: ["Ka = 1 x 10⁻⁵",
                    "Ka = 1 x 10⁻³",
                    "Ka = 1 x 10⁻¹",
                    "Ka = 1 x 10⁻⁷",],
                correctAnswer: 2,
            },
            {
                question: "A solution with [H₃O⁺] = 1 x 10⁻⁹ M has a pH of what?",
                options: ["5",
                    "7",
                    "11",
                    "9",],
                correctAnswer: 3,
            },
            {
                question: "The solubility product (Ksp) expression for AgCl is?",
                options: ["[AgCl]",
                    "[Ag⁺][Cl⁻]",
                    "[AgCl]/[H₂O]",
                    "1/[Ag⁺][Cl⁻]",],
                correctAnswer: 1,
            },
            {
                question: "A salt precipitates when?",
                options: ["Q < Ksp",
                    "Q > Ksp",
                    "Q = Ksp",
                    "Ksp = 0",],
                correctAnswer: 1,
            },
            {
                question: "Which salt is most soluble if all are measured at 25 °C?",
                options: ["Ksp = 1 x 10⁻¹⁰",
                    "Ksp = 1 x 10⁻⁶",
                    "Ksp = 1 x 10⁻²",
                    "Ksp = 1 x 10⁻⁸",],
                correctAnswer: 2,
            },
            {
                question: "Common ion effect occurs when...",
                options: ["A solution contains two salts with different cations",
                    "A solution contains a salt and an additional source of a common ion, lowering solubility",
                    "A strong acid and a strong base are mixed",
                    "Two buffers are mixed",],
                correctAnswer: 1,
            },
            {
                question: "Which salt is more soluble in acidic solution than in pure water?",
                options: ["NaCl",
                    "CaF₂",
                    "KNO₃",
                    "NaOH",],
                correctAnswer: 1,
            },
        ],
    },

    {
        category: "3.7 oxidation-reduction chemistry",
        questions: [
            {
                question: "Which statement defines oxidation in terms of electrons?",
                options: ["Gain of electrons",
                    "Loss of electrons",
                    "Gain of protons",
                    "Loss of protons",],
                correctAnswer: 1,
            },
            {
                question: "The oxidising agent is the species that...",
                options: ["Loses electrons",
                    "Increases oxidation number",
                    "Gains electrons",
                    "Gets reduced by another species",],
                correctAnswer: 2,
            },
            {
                question: "In the reaction: Zn + Cu²⁺ → Zn²⁺ + Cu, which species is reduced?",
                options: ["Zn",
                    "Both Zn and Cu²⁺",
                    "Zn²⁺",
                    "Cu²⁺",],
                correctAnswer: 3,
            },
            {
                question: "In the half-equation Cl₂ + 2e⁻ → 2Cl⁻, chlorine is?",
                options: ["Oxidised",
                    "Reduced",
                    "Neither oxidised nor reduced",
                    "Acting as a reducing agent",],
                correctAnswer: 1,
            },
            {
                question: "Which change in oxidation number indicates oxidation?",
                options: ["Fe²⁺ → Fe³⁺",
                    "Cl₂ → Cl⁻",
                    "Cu²⁺ → Cu",
                    "SO₄²⁻ → SO₂",],
                correctAnswer: 0,
            },
            {
                question: "In a galvanic cell, electrons flow...",
                options: ["From cathode to anode through the external circuit",
                    "From anode to cathode through the external circuit",
                    "Through the salt bridge",
                    "From high concentration to low concentration",],
                correctAnswer: 1,
            },
            {
                question: "The cathode in a galvanic cell is where...",
                options: ["Oxidation occurs",
                    "Electrons are lost",
                    "Reduction occurs",
                    "Positive ions are produced",],
                correctAnswer: 2,
            },
            {
                question: "Which component of a galvanic cell allows ions to flow and maintain electrical neutrality?",
                options: ["The external circuit",
                    "The cathode",
                    "The anode",
                    "The salt bridge",],
                correctAnswer: 3,
            },
            {
                question: "The standard hydrogen electrode is assigned a potential of:",
                options: ["-1.00 V",
                    "+1.00 V",
                    "0.00 V",
                    "+0.34 V",],
                correctAnswer: 2,
            },
            {
                question: "If E°(Zn²⁺/Zn) = -0.76 V and E°(Cu²⁺/Cu) = +0.34 V, the E°cell for Zn/Cu cell is:",
                options: ["+1.10 V",
                    "-1.10 V",
                    "+0.42 V",
                    "-0.42 V",],
                correctAnswer: 0,
            },
            {
                question: "Electrolysis differs from a galvanic cell because:",
                options: ["It is spontaneous",
                    "It involves only oxidation reactions",
                    "Electrons flow from cathode to anode",
                    "It requires an external power source",],
                correctAnswer: 3,
            },
            {
                question: "During the electrolysis of molten NaCl...",
                options: ["Sodium forms at the cathode",
                    "Chlorine forms at the cathode",
                    "Sodium forms at the anode",
                    "Chlorine forms at the salt bridge",],
                correctAnswer: 0,
            },
            {
                question: "In electrolysis, the cathode is always...",
                options: ["Positive",
                    "Neutral",
                    "Negative",
                    "The site of oxidation",],
                correctAnswer: 2,
            },
            {
                question: "Electroplating occurs by?",
                options: ["Oxidising the object to be plated",
                    "Reducing metal ions onto the object's surface",
                    "Dissolving the metal being plated",
                    "Percipitating insoluble salts",],
                correctAnswer: 1,
            },
            {
                question: "Which product forms at the anode during the electrolysis of aqueous CuSO₄?",
                options: ["Cu²⁺",
                    "Cu metal",
                    "O₂ gas",
                    "H₂ gas",],
                correctAnswer: 2,
            },
            {
                question: "Which definition describes standard electrode potential (E°)?",
                options: ["The potential difference of a cell under any conditions",
                    "The potential of a half-cell under standard conditions relative to SHE",
                    "The voltage of a cell when concentration is high",
                    "The energy released in electrolysis",],
                correctAnswer: 1,
            },
            {
                question: "Which metal is the strongest reducing agent?",
                options: ["E° = +0.80 V",
                    "E° = +0.34 V",
                    "E° = -0.76 V",
                    "E° = 0.00 V",],
                correctAnswer: 2,
            },
            {
                question: "Which factor does not affect the value of E°cell?",
                options: ["Temperature",
                    "Pressure",
                    "Concentration",
                    "Identity of the substances",],
                correctAnswer: 3,
            },
            {
                question: "A positive E°cell means?",
                options: ["The reaction is non-spontaneous",
                    "The reaction is spontaneous",
                    "The cell will not function",
                    "Reduction cannot occur",],
                correctAnswer: 1,
            },
            {
                question: "The E°cell for a Daniell cell (Zn/Cu) under standard conditions is:",
                options: ["+1.10 V",
                    "-0.76 V",
                    "+0.34 V",
                    "0.00 V",],
                correctAnswer: 0,
            },
            {
                question: "Which process describes corrosion of iron?",
                options: ["Oxidation of Fe → Fe²⁺, followed by reaction with O₂/H₂O",
                    "Reduction of Fe²⁺ to Fe",
                    "Electrolysis of FeCl₂",
                    "Decomposition of Fe by heat",],
                correctAnswer: 0,
            },
            {
                question: "Galvanisation protects iron by?",
                options: ["Painting the surface",
                    "Alloying with copper",
                    "Using oil to prevent water contact",
                    "Coating with zinc, which acts as a sacrificial anode",],
                correctAnswer: 3,
            },
            {
                question: "A sacrificial anode works because?",
                options: ["It has a more positive E° value than iron",
                    "It oxidises more readily than iron",
                    "It reduces water to hydrogen gas",
                    "It prevents oxygen contact",],
                correctAnswer: 1,
            },
            {
                question: "In a rechargeable battery...",
                options: ["Only oxidation occurs",
                    "Both reactions are irreversible",
                    "Both oxidation and reduction reactions can be reversed by applying a voltage",
                    "Only hydrogen is formed",],
                correctAnswer: 2,
            },
            {
                question: "The main role of a salt bridge in a galvanic cell is to?",
                options: ["Allow electrons to flow",
                    "Provide a pathway for oxidation",
                    "Increase cell voltage",
                    "Provide ions to balance charges",],
                correctAnswer: 3,
            },
        ],
    },

    {
        category: "3.2 spectroscopic chemistry",
        questions: [
            {
                question: "Which of the following is the main use of spectroscopy in organic chemistry?",
                options: ["To measure reaction enthalpy",
                    "To determine molecular structure",
                    "To increase yield in reactions",
                    "To seperate mixtures",],
                correctAnswer: 1,
            },
            {
                question: "Which technique gives information about the molecular mass of a compound?",
                options: ["IR spectroscopy",
                    "¹H NMR",
                    "Mass spectrometry",
                    "¹³C NMR",],
                correctAnswer: 2,
            },
            {
                question: "Define the term molecular ion peak in mass spectrometry.",
                options: ["Peak caused by the base fragment",
                    "Peak caused by the ion containing the full molecule mass",
                    "Peak caused by loss of H₂O",
                    "Peak caused by isotopes only",],
                correctAnswer: 1,
            },
            {
                question: "What does the base peak in a mass spectrum represent?",
                options: ["The lightest fragment",
                    "The heaviest fragment",
                    "The peak due to isotopes",
                    "The tallest peak, assigned 100% relative abundance",],
                correctAnswer: 3,
            },
            {
                question: "Which isotope causes a noticeable M+2 peak in mass spectra of molecules containing chlorine?",
                options: ["³⁵Cl and ³⁷Cl",
                    "¹²C",
                    "¹H",
                    "¹⁴N",],
                correctAnswer: 0,
            },
            {
                question: "In IR spectroscopy, the region around 1700 cm⁻¹ is characteristic of...",
                options: ["O-H stretching",
                    "C-C stretching",
                    "C=O stretching",
                    "C-H bending",],
                correctAnswer: 2,
            },
            {
                question: "A broad absorption around 3200-3600 cm⁻¹ is typical for...",
                options: ["C-H bond",
                    "O-H bond",
                    "N-H bond",
                    "C≡C bond",],
                correctAnswer: 1,
            },
            {
                question: "Which functional group shows an IR absorption near 1720 cm⁻¹ and there is no broad OH peak?",
                options: ["Carboxylic acid",
                    "Aldehyde",
                    "Alcohol",
                    "Ketone",],
                correctAnswer: 3,
            },
            {
                question: "What IR region would you examine to confirm the presence of a C-H bond in an alkene?",
                options: ["1000-1200 cm⁻¹",
                    "3000-3100 cm⁻¹",
                    "2800-3000 cm⁻¹",
                    "1600-1700 cm⁻¹",],
                correctAnswer: 1,
            },
            {
                question: "A broad IR absorption near 2500-3300 cm⁻¹ and a sharp peak near 1700 cm⁻¹ likely indicate a:",
                options: ["Ketone",
                    "Alcohol",
                    "Carboxylic acid",
                    "Ester",],
                correctAnswer: 2,
            },
            {
                question: "In ¹³C NMR spectroscopy, each unique carbon environment will show...",
                options: ["A multiplet",
                    "A doublet",
                    "A single peak",
                    "A base peak",],
                correctAnswer: 2,
            },
            {
                question: "A peak around δ = 200 ppm in a ¹³C NMR spectrum is typical of...",
                options: ["Alkene carbon",
                    "Carboxylic carbon",
                    "Carbon in a carbonyl group (ketone)",
                    "Aromatic carbon",],
                correctAnswer: 2,
            },
            {
                question: "A compound with 4 carbon atoms shows only 2 signals in its ¹³C NMR spectrum. This suggests that...",
                options: ["A straight-chain isomer is present",
                    "There are two pairs of equivalent carbon atoms",
                    "All carbons are different",
                    "It is a carboxylic acid",],
                correctAnswer: 1,
            },
            {
                question: "A ¹³C NMR peak at δ = 50 ppm is likely due to...",
                options: ["Methyl carbon",
                    "Carbon attached to oxygen (e.g., alcohol or ether)",
                    "Aromatic carbon",
                    "Carbonyl carbon",],
                correctAnswer: 1,
            },
            {
                question: "Which carbon would most likely appear furthest downfield in ¹³C NMR?",
                options: ["CH₃ group",
                    "Aldehyde carbon",
                    "Ketone carbon",
                    "Alcohol carbon",],
                correctAnswer: 2,
            },
            {
                question: "A compound shows: Molecular ion at m/z = 88, strong IR absorption at 1735 cm⁻¹, ¹³C NMR peak at δ = 170 ppm. Which functional group is most likely present?",
                options: ["Alcohol",
                    "Carboxylic acid",
                    "Ester",
                    "Aldehyde",],
                correctAnswer: 2,
            },
            {
                question: "Which combination of spectroscopic features is consistent with an aldehyde?",
                options: ["IR: 1720 cm⁻¹ and 2700 cm⁻¹; ¹³C NMR: δ = 200 ppm",
                    "IR: Broad peak at 3300 cm⁻¹; ¹³C NMR: δ = 50 ppm",
                    "IR: 1600 cm⁻¹; ¹³C NMR: δ = 120 ppm",
                    "IR: Sharp 1735 cm⁻¹; ¹³C NMR: δ = 170 ppm",],
                correctAnswer: 0,
            },
            {
                question: "The combination of a strong IR absorption at 1715 cm⁻¹ and a ¹³C NMR signal at δ = 210 ppm suggests:",
                options: ["Ester",
                    "Carboxylic acid",
                    "Alcohol",
                    "Ketone",],
                correctAnswer: 3,
            },
            {
                question: "What does the intensity of a peak in ¹³C NMR typically represent?",
                options: ["Number of equivalent carbon atoms",
                    "Chemical shift",
                    "Relative abundance of that carbon",
                    "Number of attached hydrogens",],
                correctAnswer: 0,
            },
            {
                question: "The number of peaks in a ¹³C NMR spectrum helps identify:",
                options: ["The mass of the molecule",
                    "The number of hydrogen atoms",
                    "The number of unique carbon environments",
                    "The polarity of the compound",],
                correctAnswer: 2,
            },
            {
                question: "In mass spectrometry, fragmentation patterns are useful for...",
                options: ["Determining IR absorptions",
                    "Determining molecular mass of the compound only",
                    "Measuring chemical shifts",
                    "Identifying possible structures and functional groups",],
                correctAnswer: 3,
            },
            {
                question: "What is the main reason ¹³C NMR spectra are simpler than ¹H NMR spectra?",
                options: ["Carbon nuclei are less magnetic, therefore easier to measure",
                    "¹³C has no spin",
                    "¹³C is less abundant and rarely couples",
                    "Carbon is not detected directly",],
                correctAnswer: 2,
            },
            {
                question: "You are given the molecular formula C₄H₈O₂. Which spectroscopy technique would most directly confirm the presence of a carboxylic acid group?",
                options: ["Mass spectrometry",
                    "¹³C NMR spectroscopy",
                    "IR spectroscopy",
                    "UV-Vis spectroscopy",],
                correctAnswer: 2,
            },
            {
                question: "Which of the following does ¹³C NMR spectroscopy NOT do?",
                options: ["Allows identification of carbon environments",
                    "Provides the exact molecular mass of the compound",
                    "Provides information about molecular symmetry",
                    "Confirms the presence of very specific functional groups",],
                correctAnswer: 1,
            },
            {
                question: "What is the primary purpose of utilising spectroscopic techniques in organic chemistry?",
                options: ["To measure melting points of compounds",
                    "To determine the color and shape of organic compounds",
                    "To identify the structure and functional groups of molecules",
                    "To separate mixtures of compounds to use in seperate reactions",],
                correctAnswer: 2,
            },
        ],
    },

    {
        category: "3.3 chemical processes",
        questions: [
            {
                question: "Which gas is a major contributor to acid rain?",
                options: ["Methane (CH₄)",
                    "Sulfur dioxide (SO₂)",
                    "Oxygen (O₂)",
                    "Nitrogen gas (N₂)",],
                correctAnswer: 1,
            },
            {
                question: "Acid rain forms when sulfur dioxide reacts with...",
                options: ["Hydrogen gas",
                    "Water and Oxygen",
                    "Carbon monoxide",
                    "Methane gas",],
                correctAnswer: 1,
            },
            {
                question: "Which is a main cause of sulfur dioxide emissions?",
                options: ["Car exhaust emissions",
                    "Forest fires",
                    "Rusting of iron",
                    "Volcanic eruptions & coal combustion",],
                correctAnswer: 3,
            },
            {
                question: "One effect of acid rain on the environment is:",
                options: ["Neutralisation of soil",
                    "Increased fish population",
                    "Damage to limestone buildings",
                    "Faster photosynthesis for plants",],
                correctAnswer: 2,
            },
            {
                question: "Which chemical process is used to extract gold from ore using cyanide?",
                options: ["Electrolysis",
                    "Cyanidation (leaching)",
                    "Fractional distillation",
                    "Polymerisation of the ore using cyanide to seperate the gold from the rock",],
                correctAnswer: 1,
            },
            {
                question: "In the gold cyanidation process, gold reacts with...",
                options: ["Hydrochloric acid",
                    "Sodium hydroxide",
                    "Sodium cyanide and oxygen",
                    "Sulfuric acid",],
                correctAnswer: 2,
            },
            {
                question: "What is one environmental chemical risk of using cyanide in mining?",
                options: ["Acidification of lakes, thus damaging marine life",
                    "Ozone layer depletion",
                    "Eutrophication",
                    "Toxic leaks into waterways",],
                correctAnswer: 3,
            },
            {
                question: "Which of the following is a greenhouse gas?",
                options: ["O₂",
                    "CO₂",
                    "N₂",
                    "Ar",],
                correctAnswer: 1,
            },
            {
                question: "Greenhouse gases are a major environmental issue because they trap...",
                options: ["Oxygen",
                    "Sound energy",
                    "Heat energy",
                    "UV radiation",],
                correctAnswer: 2,
            },
            {
                question: "Ocean acidification is caused by...",
                options: ["Sulfur dioxide dissolving in seawater",
                    "Nitrogen gas increasing in oceans",
                    "Carbon dioxide dissolving in seawater, thus producing carbonic acid",
                    "Loss of marine life",],
                correctAnswer: 2,
            },
            {
                question: "A consequence of ocean acidification is...",
                options: ["Coral bleaching and weaker shells in marine life",
                    "Stronger coral reefs",
                    "Increased oxygen levels in water, which are bad for the marine life",
                    "More photosynthesis in algae, meaning they spread more",],
                correctAnswer: 0,
            },
            {
                question: "Fertilisers can lead to water pollution through a chemical process called what?",
                options: ["Neutralisation",
                    "Evaporation",
                    "Eutrophication",
                    "Sublimation",],
                correctAnswer: 2,
            },
            {
                question: "Eutrophication results in...",
                options: ["More fish",
                    "Growth of algae and less oxygen in water",
                    "Cleaner rivers",
                    "Neutral pH in lakes",],
                correctAnswer: 1,
            },
            {
                question: "The active ingredient in many fertilisers is:",
                options: ["Oxygen",
                    "Nitrogen compounds",
                    "Carbon",
                    "Glucose",],
                correctAnswer: 1,
            },
            {
                question: "Nitrogen from fertilisers can enter waterways mainly through...",
                options: ["Runoff",
                    "Condensation",
                    "Combustion",
                    "Boiling",],
                correctAnswer: 0,
            },
            {
                question: "Which compound is commonly used to treat acidic soil?",
                options: ["Sodium chloride",
                    "Calcium carbonate",
                    "Magnesium sulfate",
                    "Silicon dioxide",],
                correctAnswer: 1,
            },
            {
                question: "Ozone in the upper atmosphere protects us from?",
                options: ["Acid rain",
                    "Visible light",
                    "Infrared radiation",
                    "UV radiation",],
                correctAnswer: 3,
            },
            {
                question: "Ozone is a molecule made of:",
                options: ["2 Oxygen atoms",
                    "1 Oxygen atom",
                    "3 Oxygen atoms",
                    "4 Oxygen atoms",],
                correctAnswer: 2,
            },
            {
                question: "In water treatment, what is the purpose of adding chlorine?",
                options: ["Neutralising the water",
                    "Eliminate heavy metals",
                    "Soften the water",
                    "Eliminate any bacteria",],
                correctAnswer: 3,
            },
            {
                question: "In the process of photosynthesis, what is the chemical that absorbs light energy?",
                options: ["ATP",
                    "Glucose",
                    "Chlorophyll",
                    "Oxygen",],
                correctAnswer: 2,
            },
            {
                question: "In gold cyanidation, the gold dissolves by forming a complex ion. What is the formula of this complex?",
                options: ["Au(CN)₂⁻",
                    "AuCl₄⁻",
                    "Au³⁺",
                    "AuOH",],
                correctAnswer: 0,
            },
            {
                question: "Why is oxygen necessary in the gold cyanidation process?",
                options: ["It acts as a reducing agent",
                    "It reacts with cyanide to form harmless products",
                    "It oxidizes gold metal to soluble gold complexes",
                    "It neutralizes cyanide ions producing pure gold",],
                correctAnswer: 2,
            },
            {
                question: "Which of the following gases is the LEAST significant contributor to acid rain?",
                options: ["Sulfur dioxide (SO₂)",
                    "Nitrogen dioxide (NO₂)",
                    "Carbon dioxide (CO₂)",
                    "Nitric oxide (NO)",],
                correctAnswer: 2,
            },
            {
                question: "Acid rain can lead to the leaching of which harmful metal from soils into waterways?",
                options: ["Sodium",
                    "Calcium",
                    "Potassium",
                    "Lead",],
                correctAnswer: 3,
            },
            {
                question: "What is the oxidation state of gold (Au) in the complex ion Au(CN)₂⁻ used in gold cyanidation?",
                options: ["0",
                    "+1",
                    "+2",
                    "-1",],
                correctAnswer: 1,
            },
        ]
    }
]